### PR TITLE
feat: optimize trajectory integration and fix Apple Clang template ambiguity

### LINKED ISSUE #6003: [Humble][macOS] Build Failure in nav2_mppi_controller on macOS (Apple Clang xtensor template ambiguity)
## Description

When building `nav2_mppi_controller` from source on **macOS (Tahoe, Apple Silicon ARM64)** for the **ROS 2 Humble** distribution, the build fails during compilation of `optimizer.cpp` and related motion model files.

The issue is triggered by the interaction between **xtensor v0.25.0** and **Apple Clang (17.0+)**, resulting in ambiguous template specialization errors.

---

## The Problem

The core failure originates in **xtensor's internal template metaprogramming**, specifically when rebinding internal storage containers such as `xt::svector`.

Apple Clang cannot distinguish between `long` and `unsigned long` during partial template specialization, resulting in:

---
## Upstream Reference (Ongoing Issue)

This build failure appears to be related to an existing xtensor issue concerning ambiguous partial template specializations on Apple Clang:

🔗 https://github.com/xtensor-stack/xtensor/issues/2804

---
## The Error

```bash
clang++: warning: argument unused during compilation: '-msse4.2' [-Wunused-command-line-argument]

In file included from <workspace>/src/navigation2/nav2_mppi_controller/src/optimizer.cpp:15:
In file included from <workspace>/src/navigation2/nav2_mppi_controller/include/nav2_mppi_controller/optimizer.hpp:21:
In file included from <install>/include/xtensor/xtensor.hpp:19:
In file included from <install>/include/xtensor/xbuffer_adaptor.hpp:21:
In file included from <install>/include/xtensor/xstorage.hpp:23:
In file included from <install>/include/xtensor/xtensor_simd.hpp:17:
<install>/include/xtensor/xutils.hpp:896:31: error: ambiguous partial specializations of 'rebind_container<long, xt::svector<unsigned long>>'
  using type = typename rebind_container<std::ptrdiff_t, S>::type;
                              ^

<install>/include/xtensor/xutils.hpp:883:12: note: partial specialization matches [with X = long, C = xt::svector, T = unsigned long, N = 4]
  struct rebind_container<X, C<T, N>>
         ^

<install>/include/xtensor/xstorage.hpp:1415:12: note: partial specialization matches [with X = long, T = unsigned long, N = 4, A = std::allocator<unsigned long>, B = true]
  struct rebind_container<X, svector<T, N, A, B>>
         ^

[...]

<install>/include/xtensor/xiterable.hpp:45:50: error: no type named 'stepper' in 
'xt::xiterable_inner_types<
  xt::xarray_container<
    xt::uvector<float, xsimd::aligned_allocator<float>>,
    xt::layout_type::row_major,
    xt::svector<unsigned long>
  >
>'

<install>/include/xtensor/xcontainer.hpp:140:15: error: using declaration refers into 
'accessible_base::', which is not a base class of 
'xcontainer<
  xt::xarray_container<
    xt::uvector<float, xsimd::aligned_allocator<float>>,
    xt::layout_type::row_major,
    xt::svector<unsigned long>
  >
>'

[...]

<install>/include/xtensor/xmath.hpp:2288:16: note: in instantiation of function template specialization 
'xt::accumulate<...>' requested here

<src>/navigation2/nav2_mppi_controller/src/optimizer.cpp:344:9: note: 
in instantiation of function template specialization 
'xt::cumsum<void, xt::xfunction<...>>' requested here
  xt::cumsum(state.wz * settings_.model_dt, 1) + initial_yaw;
      ^

<src>/navigation2/nav2_mppi_controller/src/optimizer.cpp:364:5: error: no matching function for call to 'cumsum'
  xt::cumsum(dx * settings_.model_dt, 1);
      ^

<src>/navigation2/nav2_mppi_controller/src/optimizer.cpp:366:5: error: no matching function for call to 'cumsum'
  xt::cumsum(dy * settings_.model_dt, 1);
      ^

14 errors generated.
make[2]: *** [CMakeFiles/mppi_controller.dir/src/optimizer.cpp.o] Error 1
make[1]: *** [CMakeFiles/mppi_controller.dir/all] Error 2
make: *** [all] Error 2
make: INTERNAL: Exiting with 9 jobserver tokens available; should be 8!
```
---

## Affected Components

- `xt::cumsum`  
  - Fails during trajectory integration.
- `xt::masked_view`  
  - Breaks in vehicle constraint applications.
- `xt::xarray`  
  - Recursive template instantiation failures due to dynamic rank deduction.

---

### 1️⃣ Type Ambiguity on macOS
On Darwin systems, `size_t` may resolve to types that match multiple template specializations simultaneously (`long` vs `unsigned long`).

### 2️⃣ Dynamic Rank Complexity
`xt::xarray` relies on runtime dimensionality tracking, increasing template recursion depth and exposing Clang’s strict specialization resolution behavior.

### 3️⃣ Apple Clang Strictness
Apple Clang enforces stricter template specialization resolution compared to GCC, exposing ambiguity in `xtensor 0.25.0`.

---

## Temp Solution

Commit: https://github.com/idesign0/id_navigation2/commit/edce854519f47e8ff064891e519802f9b2b64a3f

## Environment

- **ROS 2 Distro:** Humble  
- **OS:** macOS 26.3 (25D125) — Apple Silicon (ARM64)  
- **Compiler:** Apple Clang 17.0.0 (clang-1700.6.4.2)  
- **Target:** arm64-apple-darwin25.3.0  
- **Toolchain:** XcodeDefault.xctoolchain  
- **xtensor Version:** 0.25.0

### PR DESCRIPTION
**Pull request by idesign0**
## Description
  This PR resolves build-blocking template ambiguity on macOS (Apple Clang) and introduces a performance optimization for trajectory integration in the MPPI controller.

  ### Key Changes
  - **Isolated Workarounds**: Created `apple_utils.hpp` to house manual `cumsum` implementations, bypassing `xtensor` template issues specific to the Clang compiler.
  - **Abstraction Layer**: Implemented `Cumsum1DOp` and `Cumsum2DOp` aliases in `optimizer.hpp`. This centralizes the platform-specific logic, allowing the core controller code to remain clean and free of `#ifdef` blocks.
  - **Performance Optimization**: Updated the smoothing filter and internal utilities to use fixed-rank `xt::xtensor<float, 1>` instead of `xarray`. This assists with type deduction and improves execution speed across all platforms.

  ## Performance Benchmarks (macOS ARM64)
  Benchmarks were conducted in Release mode (`-O3`) over 1,000,000 iterations with a 100-step horizon.

  | Operation | Original `xtensor` | **Manual (This PR)** | Improvement |
  | :--- | :--- | :--- | :--- |
  | **1D Cumsum** | 0.367784 µs | **0.13083 µs** | **~35% faster** |
  | **2D Cumsum** | 0.509195 µs | **0.218972 µs** | **~43% faster** |

  

  ## Testing & Verification
  The full project currently fails to compile on macOS with the existing `xt::cumsum` calls. Verification was performed using an isolated benchmark script to compare the standard library against the manual implementation. 

  **Compilation command used for verification:**
  ```bash
  clang++ -O3 -std=c++17 benchmark.cpp \
    -I ~/humble-ros2/install/include \
    -I ./include \
    -o bench
  ```
  
   The following script was used to generate the results:
   
 ```cpp
#include <chrono>
#include <iostream>
#include <xtensor/xtensor.hpp>
#include <xtensor/xmath.hpp> 
#include "nav2_mppi_controller/tools/apple_utils.hpp"

void benchmark_1d_manual(const size_t size, const int iterations) {
    xt::xtensor<float, 1> data = xt::ones<float>({size}) * 0.1f;
    auto start = std::chrono::high_resolution_clock::now();
    float sink = 0.0f;
    for (int i = 0; i < iterations; ++i) {
        auto res = mppi::utils::manual_cumsum_1d(data);
        sink += res(size - 1);
    }
    auto end = std::chrono::high_resolution_clock::now();
    std::cout << "1D Manual:   " << (std::chrono::duration<double>(end-start).count() / iterations) * 1e6 << " us" << std::endl;
}

void benchmark_1d_original(const size_t size, const int iterations) {
    xt::xtensor<float, 1> data = xt::ones<float>({size}) * 0.1f;
    auto start = std::chrono::high_resolution_clock::now();
    float sink = 0.0f;
    for (int i = 0; i < iterations; ++i) {
        auto res = xt::cumsum(data, 0); 
        sink += res(size - 1);
    }
    auto end = std::chrono::high_resolution_clock::now();
    std::cout << "1D Original: " << (std::chrono::duration<double>(end-start).count() / iterations) * 1e6 << " us" << std::endl;
}

void benchmark_2d_manual(const size_t rows, const size_t cols, const int iterations) {
    xt::xtensor<float, 2> data = xt::ones<float>({rows, cols}) * 0.1f;
    auto start = std::chrono::high_resolution_clock::now();
    float sink = 0.0f;
    for (int i = 0; i < iterations; ++i) {
        auto res = mppi::utils::manual_cumsum_2d(data, 0);
        sink += res(rows - 1, cols - 1);
    }
    auto end = std::chrono::high_resolution_clock::now();
    std::cout << "2D Manual:   " << (std::chrono::duration<double>(end-start).count() / iterations) * 1e6 << " us" << std::endl;
}

void benchmark_2d_original(const size_t rows, const size_t cols, const int iterations) {
    xt::xtensor<float, 2> data = xt::ones<float>({rows, cols}) * 0.1f;
    auto start = std::chrono::high_resolution_clock::now();
    float sink = 0.0f;
    for (int i = 0; i < iterations; ++i) {
        auto res = xt::cumsum(data, 0);
        sink += res(rows - 1, cols - 1);
    }
    auto end = std::chrono::high_resolution_clock::now();
    std::cout << "2D Original: " << (std::chrono::duration<double>(end-start).count() / iterations) * 1e6 << " us" << std::endl;
}

int main() {
    const int iterations = 1000000;
    const size_t size = 100;
    benchmark_1d_manual(size, iterations);
    benchmark_1d_original(size, iterations);
    benchmark_2d_manual(size, 3, iterations);
    benchmark_2d_original(size, 3, iterations);
    return 0;
}
```

## Related Issues
  Fixes #6003

### CODE REVIEW

File: nav2_mppi_controller/include/nav2_mppi_controller/optimizer.hpp [hunk 1]
```diff
@@ -259,6 +263,24 @@ class Optimizer
...
+#else
+  // Linux/Others: Use standard xtensor
+  static constexpr Cumsum1DOp cumsum_1d_op = [](const xt::xtensor<float, 1>& x) {
+    return xt::cumsum(x, 0);
+  };
+  static constexpr Cumsum2DOp cumsum_2d_op = [](const xt::xtensor<float, 2>& x, int axis) {
+    return xt::cumsum(x, axis);
+  };
+#endif
+
```
Comment (mini-1235) [inline nav2_mppi_controller/include/nav2_mppi_controller/optimizer.hpp]: I think we can do something like this:
```
  template <typename E>
  inline auto cumsum_1d(const E & expression) {
  #ifdef __APPLE__
    return utils::manual_cumsum_1d(expression);
  #else
    return xt::cumsum(expression, 0);
  #endif
  }

 template <typename E>
 inline auto cumsum_2d(const E & expression, int axis) {
 #ifdef __APPLE__
   return utils::manual_cumsum_2d(expression, axis);
 #else
   return xt::cumsum(expression, axis);
 #endif
 }
```

**Review by mini-1235 — COMMENTED** [review]
@idesign0 can you also check the CI and fix them: https://app.circleci.com/pipelines/github/ros-navigation/navigation2/18189/workflows/4fe78a15-b205-4ebd-a3c1-2fce52bf56c8/jobs/54764 

Otherwise LGTM

File: nav2_mppi_controller/include/nav2_mppi_controller/optimizer.hpp (hunk 1 above)
Comment (idesign0) [reply nav2_mppi_controller/include/nav2_mppi_controller/optimizer.hpp]: yes looks clean! will get back to you with the update and pre-commit related changes. :D

File: nav2_mppi_controller/src/bench
Comment (SteveMacenski) [inline nav2_mppi_controller/src/bench:1]: Should we remove this?

File: nav2_mppi_controller/src/benchmark.cpp
Comment (SteveMacenski) [inline nav2_mppi_controller/src/benchmark.cpp:1]: I think this can be removed. This was really useful for the PR discussion but not sure this is useful in general to commit to the project

**Review by SteveMacenski — COMMENTED** [review]
Otherwise, approved!

File: nav2_mppi_controller/src/bench
Comment (idesign0) [reply nav2_mppi_controller/src/bench:1]: Sorry added by mistake when i was adding pre-commit changes. 😅. Will remove them.

File: nav2_mppi_controller/src/benchmark.cpp
Comment (idesign0) [reply nav2_mppi_controller/src/benchmark.cpp:1]: This one as well added by mistake.  Will fix it. :)

File: nav2_mppi_controller/include/nav2_mppi_controller/motion_models.hpp [hunk 2]
```diff
@@ -113,8 +113,9 @@ class AckermannMotionModel : public MotionModel
     auto & vx = control_sequence.vx;
     auto & wz = control_sequence.wz;
 
-    auto view = xt::masked_view(wz, (xt::fabs(vx) / xt::fabs(wz)) < min_turning_r_);
-    view = xt::sign(wz) * xt::fabs(vx) / min_turning_r_;
+    auto condition = (xt::fabs(vx) / xt::fabs(wz)) < min_turning_r_;
+    auto constrained_wz = xt::eval(xt::sign(wz) * xt::fabs(vx) / min_turning_r_);
+    wz = xt::where(condition, constrained_wz, wz);
```
Comment (SteveMacenski) [inline nav2_mppi_controller/include/nav2_mppi_controller/motion_models.hpp]: Are there performance changes from this?

Comment (idesign0) [reply nav2_mppi_controller/include/nav2_mppi_controller/motion_models.hpp]: that has slipped my mind. will come back to you with the stats.

Comment (idesign0) [reply nav2_mppi_controller/include/nav2_mppi_controller/motion_models.hpp]: @SteveMacenski  I benchmarked three approaches for the `wz` minimum turning radius:

  | Method       | Avg time (ns) |
  |-------------|---------------|
  | masked_view  | 29,361        |
  | xt::where    | 33,292        |
  | manual loop  | 9,973         |

  **Summary:** The manual loop eliminates temporaries, performs in-place updates, and is ~3× faster than `masked_view` and ~3.3× faster than `xt::where`, making it the most efficient choice for high-frequency MPPI updates. 
  
  
The following script was used to generate these metrics:

````cpp
#include <iostream>
#include <xtensor/xarray.hpp>
#include <xtensor/xmath.hpp>
#include <xtensor/xmasked_view.hpp>
#include <chrono>

using namespace std::chrono;

// ---------------- Functions ----------------
double benchmark_masked_view(const xt::xarray<double>& vx, const xt::xarray<double>& wz, double min_turning_r_, size_t iterations)
{
    double total_time = 0.0;
    for (size_t iter = 0; iter < iterations; ++iter)
    {
        auto wz_copy = wz;
        auto start = high_resolution_clock::now();

        // --- masked view logic ---
        auto view = xt::masked_view(wz_copy, (xt::fabs(vx) / xt::fabs(wz_copy)) < min_turning_r_);
        view = xt::sign(wz_copy) * xt::fabs(vx) / min_turning_r_;

        auto end = high_resolution_clock::now();
        total_time += duration<double, std::nano>(end - start).count();
    }
    return total_time / iterations; // average per iteration
}

double benchmark_where(const xt::xarray<double>& vx, const xt::xarray<double>& wz, double min_turning_r_, size_t iterations)
{
    double total_time = 0.0;
    for (size_t iter = 0; iter < iterations; ++iter)
    {
        auto wz_copy = wz;
        auto start = high_resolution_clock::now();

        // --- xt::where logic ---
        auto abs_vx = xt::fabs(vx);
        auto abs_wz = xt::fabs(wz_copy);
        auto condition = (abs_vx / abs_wz) < min_turning_r_;
        wz_copy = xt::where(condition, xt::sign(wz_copy) * abs_vx / min_turning_r_, wz_copy);

        auto end = high_resolution_clock::now();
        total_time += duration<double, std::nano>(end - start).count();
    }
    return total_time / iterations;
}

double benchmark_manual_loop(const xt::xarray<double>& vx, const xt::xarray<double>& wz, double min_turning_r_, size_t iterations)
{
    double total_time = 0.0;
    for (size_t iter = 0; iter < iterations; ++iter)
    {
        auto wz_copy = wz;
        auto start = high_resolution_clock::now();

        // --- manual loop logic ---
        auto abs_vx = xt::fabs(vx);
        auto abs_wz = xt::fabs(wz_copy);
        for (size_t i = 0; i < wz_copy.size(); ++i)
        {
            if ((abs_vx[i] / abs_wz[i]) < min_turning_r_)
                wz_copy[i] = std::copysign(abs_vx[i] / min_turning_r_, wz_copy[i]);
        }

        auto end = high_resolution_clock::now();
        total_time += duration<double, std::nano>(end - start).count();
    }
    return total_time / iterations;
}

// ---------------- Main ----------------
int main()
{
    const size_t N = 100;       // array size
    const size_t iterations = 1000000;  // repeat for averaging
    const double min_turning_r_ = 1.0;

    xt::xarray<double> vx = xt::ones<double>({N});
    xt::xarray<double> wz = 5.0 * xt::ones<double>({N});

    double avg_masked = benchmark_masked_view(vx, wz, min_turning_r_, iterations);
    double avg_where = benchmark_where(vx, wz, min_turning_r_, iterations);
    double avg_loop = benchmark_manual_loop(vx, wz, min_turning_r_, iterations);

    std::cout << "Average time (ns) per iteration:\n";
    std::cout << "masked_view : " << avg_masked << " ns\n";
    std::cout << "xt::where    : " << avg_where << " ns\n";
    std::cout << "manual loop  : " << avg_loop << " ns\n";

    return 0;
}
````

**Comment by SteveMacenski** [comment]
Can you fix the linting bits? This makes it hard to review given all the other changes (and CI fails as a result)

**Comment by idesign0** [comment]
> Your linter changes are making CI fail; please remove them. Otherwise other than below the rest are approved.

got laptop access just now. : D

**Comment by mini-1235** [comment]
@idesign0 https://app.circleci.com/pipelines/github/ros-navigation/navigation2/18228/workflows/ff25c7ac-8df6-42ef-989d-b1257d6fcc02/jobs/54912/tests still failing :(

**Comment by idesign0** [comment]
> @idesign0 https://app.circleci.com/pipelines/github/ros-navigation/navigation2/18228/workflows/ff25c7ac-8df6-42ef-989d-b1257d6fcc02/jobs/54912/tests still failing :(

fixed! :)
