### PR TITLE
Checking for NAN before publishing AMCL pose

### LINKED ISSUE #591: amcl_pose doesn't track to initial_pose on Turtlebot3
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - master branch 03/01/19
- Version or commit hash:
  - b03543bc35e53c509a0832d48a1fa8e6429c685f
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
Running on turtlebot3, following instructions here:
http://emanual.robotis.com/docs/en/platform/turtlebot3/ros2/#ros2

launch nav2_bringup_1st_launch.py

click in RVIZ to set initialpose

#### Expected behavior
initialpose and amcl_pose should be very close in value

#### Actual behavior
initialpose:
```
robot@NUC1804:~$ ros2 topic echo /initialpose
Failed to load entry point 'create_key': No module named 'lxml'
Failed to load entry point 'create_keystore': No module named 'lxml'
Failed to load entry point 'create_permission': No module named 'lxml'
Failed to load entry point 'distribute_key': No module named 'lxml'
Failed to load entry point 'generate_policy': No module named 'lxml'
Failed to load entry point 'list_keys': No module named 'lxml'
header:
  stamp:
    sec: 1551487847
    nanosec: 679187026
  frame_id: map
pose:
  pose:
    position:
      x: -0.425550639629364
      y: -0.15584975481033325
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.197756564660553
      w: 0.9802511622710052
  covariance: [0.25, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.25, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.06853891945200942]
```
amcl_pose:
```
robot@NUC1804:~$ ros2 topic echo /amcl_pose
Failed to load entry point 'create_key': No module named 'lxml'
Failed to load entry point 'create_keystore': No module named 'lxml'
Failed to load entry point 'create_permission': No module named 'lxml'
Failed to load entry point 'distribute_key': No module named 'lxml'
Failed to load entry point 'generate_policy': No module named 'lxml'
Failed to load entry point 'list_keys': No module named 'lxml'
header:
  stamp:
    sec: 1551487847
    nanosec: 724581121
  frame_id: map
pose:
  pose:
    position:
      x: 1.375043147799708e+240
      y: 1.0304555720025312e+240
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.192226700885155
      w: 0.981350546678815
  covariance: [.nan, .nan, 0.0, 0.0, 0.0, 0.0, .nan, .nan, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.06680720382755952]
```
Note that amcl_pose is very different. The position x and y values are e+240, and the covariance has some "nan" values in it. I see the same type of thing in the console:
```
[INFO] [amcl]: Setting pose (1551487847.700272): 1375043147799711966983358821691779078147607432585095777168805018217076696852845761446389129032325186532263060872518598281787454690961125058046688888028460603797185730005750178805067425064757212340853091556465903337409147412568291081942204416.000 1030455572002541755991748918028617301952726955632652071252291898188713726856291767915800024551434864197199142577403987979844360196485814066280327967445199016417337350246829797343955063357713837291103586116187807986266412236670438703206760448.000 0.398
[INFO] [amcl]: AmclNode publishing pose
```
#### Additional information
I'm also seeing that the transform from map to odom is huge too.
```
robot@NUC1804:~$ ros2 run tf2_ros tf2_echo map odom
Failed to load entry point 'create_key': No module named 'lxml'
Failed to load entry point 'create_keystore': No module named 'lxml'
Failed to load entry point 'create_permission': No module named 'lxml'
Failed to load entry point 'distribute_key': No module named 'lxml'
Failed to load entry point 'generate_policy': No module named 'lxml'
Failed to load entry point 'list_keys': No module named 'lxml'
Failure at 1.55149e+09
Exception thrown:"map" passed to lookupTransform argument target_frame does not exist. 
The current list of frames is:
Frame base_footprint exists with parent odom.

Failure at 1.55149e+09
Exception thrown:"map" passed to lookupTransform argument target_frame does not exist. 
The current list of frames is:
Frame base_footprint exists with parent odom.

At time 1551488223.527508693
- Translation: [-9831012227237445380965405535651335104300466241976712586101352012869890653259456719165112935628032807334985306120810877483185162045062893143139559063884863516872593240663725401656501476875725876851993085768478706706935181989668266795605968153093949861396480.000, -1839587453652637118002950229899402937798889744636520933191631159764023308222534960244825507522662732306279588725582777877872771308124076268038822888267347168577357460688707399408539002899464036977443817423890280394031416338398894119301212684645580119474176.000, 0.000]
- Rotation: in Quaternion [0.000, 0.000, 0.092, 0.996]
```

### PR DESCRIPTION
**Pull request by mhpanah**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (fixes #591 ) |
| Primary OS tested on | (Ubuntu 18.04) |
| Robotic platform tested on |  |

---

## Description of contribution in a few bullet points
Checking for NAN in AMCL before publishing pose.

### CODE REVIEW

File: nav2_amcl/src/amcl_node.cpp [hunk 1]
```diff
@@ -845,18 +845,20 @@ AmclNode::laserReceived(sensor_msgs::msg::LaserScan::ConstSharedPtr laser_scan)
...
-         for(int i=0; i<6; i++)
-         {
-         for(int j=0; j<6; j++)
-         printf("%6.3f ", p.covariance[6*i+j]);
-         puts("");
-         }
-       */
+      float temp = 0.0;
+      for (int i = 0; i < static_cast<int>(p.pose.covariance.size()); i++) {
+        temp += p.pose.covariance[i];
```
Comment (SteveMacenski) [inline nav2_amcl/src/amcl_node.cpp]: Clever way of doing that, I like it. Out of curiousity, why not also `+=` `p.pose.pose.position.x` and `p.pose.pose.position.x` to reduce the nan checks to 1?

Comment (mhpanah) [reply nav2_amcl/src/amcl_node.cpp]: That's right. That would make less line of codes.  Will update.

File: nav2_amcl/src/amcl_node.cpp [hunk 2]
```diff
@@ -845,18 +845,18 @@ AmclNode::laserReceived(sensor_msgs::msg::LaserScan::ConstSharedPtr laser_scan)
...
+      }
+      temp += p.pose.pose.position.x + p.pose.pose.position.y;
+      if (!std::isnan(temp)) {
+        RCLCPP_INFO(get_logger(), "AmclNode publishing pose");
```
Comment (SteveMacenski) [inline nav2_amcl/src/amcl_node.cpp]: This should probably be a debug print, this would get old really fast when trying to debug other issues with a floor of these messages.

File: nav2_amcl/src/amcl_node.cpp [hunk 3]
```diff
@@ -845,18 +845,18 @@ AmclNode::laserReceived(sensor_msgs::msg::LaserScan::ConstSharedPtr laser_scan)
...
+        pose_pub_->publish(p);
+      } else {
+        RCLCPP_WARN(get_logger(), "ignoring NAN pose");
```
Comment (SteveMacenski) [inline nav2_amcl/src/amcl_node.cpp]: If there's a NaN pose/covariance in the pipe, that's really bad and probably isn't going to go away in 1 or 2 cycles, I'd make this more strongly worded and explaining what has happened. If someone sees this there's probably something very wrong with their setup and there are failing sections of safety-critical software.

Comment (mhpanah) [reply nav2_amcl/src/amcl_node.cpp]: Yes I agree, once there is a NaN the filter is diverged and it probably won't go away without resetting the filter and/or sensors.
When we enable life-cycle node, if NaN is detected we can bring AMCL node to un-configured state, check sensor values, and reset. If all fails then we can print an error message and shutdown.  But for now maybe we can just print ROS Error with "AMCL is diverged and pose is not available!"  Your thoughts?

Comment (SteveMacenski) [reply nav2_amcl/src/amcl_node.cpp]: `AMCL covariance or pose is NaN, likely due to an invalid configuration! Pose is not available!` or so

Comment (mkhansen-intel) [reply nav2_amcl/src/amcl_node.cpp]: When I was seeing this NAN it was due to a bug in the upstream data coming from the TB3, a classic "garbage in" problem. Is it possible here to verify the inputs before calculating the pose and covariance so that we reduce the likelihood of this error ever happening and points the user to the source of the problem?

Comment (SteveMacenski) [reply nav2_amcl/src/amcl_node.cpp]: That would be good. This was added here and checking in Navigation I dont see any warnings, personally, I think a crash would be an acceptable output here if a NaN gets introduced. That's an upstream issue, but a warning when you get "garbage in" would aid in debugging why its crashing so its not wrongly blamed on AMCL.
Ironically enough, that's the same type of warning I added to `robot_localization` about a year ago because I was inputting garbage sensor covariance matrices.

Comment (mhpanah) [reply nav2_amcl/src/amcl_node.cpp]: @mkhansen-intel  I can add another method in addition to this to also check for NaN for input data.

Comment (mkhansen-intel) [reply nav2_amcl/src/amcl_node.cpp]: @mhpanah - that would be great. Can you check if the input pose values are greater than the size of the map? In the TB3 case, the values were not NAN but they were like 1e30+ due to the bug. Maybe an upper bound of 10x the boundaries of the map? I'm not sure what exactly makes sense here but It seems some sanity check could be done.

File: nav2_amcl/src/amcl_node.cpp [hunk 4]
```diff
@@ -845,18 +845,18 @@ AmclNode::laserReceived(sensor_msgs::msg::LaserScan::ConstSharedPtr laser_scan)
...
-         printf("cov:\n");
-         for(int i=0; i<6; i++)
-         {
-         for(int j=0; j<6; j++)
-         printf("%6.3f ", p.covariance[6*i+j]);
-         puts("");
-         }
-       */
+      float temp = 0.0;
+      for (int i = 0; i < static_cast<int>(p.pose.covariance.size()); i++) {
```
Comment (crdelsey) [inline nav2_amcl/src/amcl_node.cpp]: I assume you're doing the static_cast<int> to silence the unsigned/signed mismatch warning? Why not just make i unsigned?

Better yet, just use the new range based for loop :

```
for( auto covariance_value : p.pose.covariance) {
  temp+= covariance_value;
}
```

File: nav2_amcl/src/amcl_node.cpp (hunk 3 above)
Comment (mhpanah) [reply nav2_amcl/src/amcl_node.cpp]: @mkhansen-intel @SteveMacenski Validating sensors data shouldn't really be AMCL's task. For example if we validate Odom data here and odom data is used elsewhere, then the other module should also implement a way to validate odom data. 

If NaN gets introduced due to invalid configuration or faulty sensor measurements, we should put the AMCL into 1) inactive state, 2) reset AMCL, 3) check for NaN, 4) repeat if it fails, 5) shutdown if problem persists.

We can do the above when life-cycle is available, however, for now not publishing AMCL pose and provide WARN should be okay temporarily.

Comment (SteveMacenski) [reply nav2_amcl/src/amcl_node.cpp]: I'm curious how you were that far off the map?

Comment (mkhansen-intel) [reply nav2_amcl/src/amcl_node.cpp]: @SteveMacenski - it was due to this bug, now fixed. I know it 'shouldn't' happen again, but it's always a good idea to have some checks on your data input where possible.
