### PR TITLE
Invalidate current_ on dynamic parameter changes

### LINKED ISSUE #5872: Planner/Controller not waiting for costmap update after dynamic param set
Follow up for https://github.com/ros-navigation/navigation2/pull/5862

## Bug report

Most dynamic parameters of costmap layers don't set `current_ = false` after they are set, which makes the planner  (or controller) not wait for the master costmap to be updated before planning. 

#### Steps to reproduce issue

1. Have a BT (see pseudo-tree below) that sets a costmap layer param like `inflation_radius` and `ComputePathToPose` directly afterwards and run it. Make sure you set the `inflation_radius` to something significantly different than the current value so you can see a difference clearly
2. You should notice that the plan is generated according to the old inflation layer. If you wait a bit and run the BT again, you should see that the new plan respects the new inflation radius, that's because the costmap had time to update

Pseudo-code BT
```
  <BehaviorTree ID="MainTree">
    <Sequence>
      <SetParamDouble
                      node_name="global_costmap/global_costmap"
                      param_name="inflation_layer_global.inflation_radius"
                      param_value="10.0"/>
      <ComputePathToPose name="Compute path"
                         goal="{goal}"
                         start="{start}"
                         use_start="false"
                         path="{path}"
                         planner_id="GridBased"
                         error_code_id="{planner_error_code_id}"/>
    </Sequence>
  </BehaviorTree>

```
1. 

#### Expected behavior

Planner/Controller waits for the new costmap to be generated

#### Actual behavior

Planner/Controller doesn't wait for the new costmap to be generated

### PR DESCRIPTION
**Pull request by MFarooq07**
Fixes #5872

When `inflation_radius`, `cost_scaling_factor`, `inflate_unknown`, or `inflate_around_unknown` parameters are changed at runtime, the InflationLayer now marks itself as not current (`current_ = false`).

Previously, these dynamic parameter updates modified internal state and triggered reinflation, but did not update the layer’s currentness flag. As a result, the master costmap could still appear current immediately after a parameter change, allowing planners/controllers to proceed using stale costmap data.

By invalidating `current_` only when the parameter value actually changes, this restores the expected behavior and allows the existing planner/controller wait logic to function correctly without introducing unnecessary costmap stalls.

---

## Basic Info

| Info | Please fill out this column |
|------|----------------------------|
| Ticket(s) this addresses | #5872 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | Not tested on hardware or simulation |
| Does this PR contain AI generated software? | No |
| Was this PR description generated by AI software? | Yes (AI-assisted rephrasing; content and technical claims manually authored and reviewed)|

---

## Description of contribution in a few bullet points

- Updated `InflationLayer::dynamicParametersCallback()` to mark the layer  as not current when inflation-affecting dynamic parameters change
- Ensures `current_` is invalidated only when parameter values actually change, avoiding unnecessary costmap recomputation
- Restores correct planner/controller behavior when planning immediately after runtime inflation parameter updates
---

## Description of documentation updates required from your changes

- No documentation updates required; this change fixes an internal correctness issue and does not introduce new parameters or user-facing behavior changes

---

## Description of how this change was tested

- Build verification: Successfully compiled `nav2_costmap_2d` on Ubuntu
- Manual verification via code trace:
  - `SetParam` triggers `dynamicParametersCallback()`
  - Layer marks itself as not current (`current_ = false`)
  - Planner/controller observes the costmap as stale and waits
  - `updateCosts()` runs and sets `current_ = true` after recomputation
- Behavior matches the reproduction steps described in the issue

---

## Future work that may be required in bullet points

- Standardize the `current_` invalidation pattern across remaining `nav2_costmap_2d` layer plugins (`obstacle_layer`, `static_layer`, `voxel_layer`, `range_sensor_layer`) to ensure consistent behavior
- Consider adding unit tests to validate layer currentness behavior on dynamic parameter updates

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists
- [ ] Should this be backported to current distributions? If so, tag with `backport-*`.

### CODE REVIEW

**Comment by tonynajjar** [comment]
let me know when the other layers are taken care of as well

**Comment by MFarooq07** [comment]
@tonynajjar Done! I've extended the fix to all affected layers:
- `obstacle_layer`: min/max_obstacle_height, enabled
- `static_layer`: enabled (with full update)
- `voxel_layer`: min/max_obstacle_height, voxel geometry params, thresholds, enabled  
- `plugin_container_layer`: enabled

Following @SteveMacenski feedback, footprint_clearing and combination_method do NOT invalidate (they apply from the next cycle onward).

Let me know if this fixes the issue.

**Comment by MFarooq07** [comment]
@SteveMacenski I was thinking of including a documentation that gives an overview of which parameters need a complete reset- parameters that need an constant update VS those which do not. This can be helpful to provide a high level understanding of layers and when/why they need to be updated/reset. The `.md` file will have the following headings. 

---
| Layer file| Parameter name  | Reset | Why |
|---|---|---:|---|
---
Let me know if that would be helpful for new users or can result in more confusion than simplification.

**Comment by MFarooq07** [comment]
@SteveMacenski kindly guide if I should fix the code formatting to avoid the errors that currently shown and submit another PR?

**Comment by SteveMacenski** [comment]
Hey, sorry, I've been setting up my new office so I've been a bit MIA building ikea furniture :laughing: 

> I was thinking of including a documentation that gives an overview of which parameters need a complete reset- parameters that need an constant update VS those which do not. 

I think some inline comments in the code for setting `current_ = false` would meet that need. I generally like the code to be self-documenting where possible. A comment saying that this invalidates the data stored would do the trick (and for ones that are not - saying so)

@tonynajjar please review quickly

**Comment by SteveMacenski** [comment]
@MFarooq07 from the CI jobs:

```

--- nav2_costmap_2d/plugins/inflation_layer.cpp
+++ nav2_costmap_2d/plugins/inflation_layer.cpp.uncrustify
@@ -448 +448,2 @@
-      if (param_name == name_ + "." + "inflation_radius" && inflation_radius_ != parameter.as_double())
+      if (param_name == name_ + "." + "inflation_radius" &&
+        inflation_radius_ != parameter.as_double())

Code style divergence in file 'nav2_costmap_2d/plugins/obstacle_layer.cpp':

--- nav2_costmap_2d/plugins/obstacle_layer.cpp
+++ nav2_costmap_2d/plugins/obstacle_layer.cpp.uncrustify
@@ -384 +384 @@
-      } else if (param_name == name_ + "." + "footprint_clearing_enabled"){
+      } else if (param_name == name_ + "." + "footprint_clearing_enabled") {

Code style divergence in file 'nav2_costmap_2d/plugins/static_layer.cpp':

--- nav2_costmap_2d/plugins/static_layer.cpp
+++ nav2_costmap_2d/plugins/static_layer.cpp.uncrustify
@@ -489,20 +489,20 @@
-  rcl_interfaces::msg::SetParametersResult
-  StaticLayer::dynamicParametersCallback(std::vector<rclcpp::Parameter> parameters)
-  {
-    std::lock_guard<Costmap2D::mutex_t> guard(*getMutex());
-    rcl_interfaces::msg::SetParametersResult result;
-
-    bool needs_full_update = false;
-
Error: -    for (auto parameter : parameters) {
-      const auto & param_type = parameter.get_type();
-      const auto & param_name = parameter.get_name();
-      if (param_name.find(name_ + ".") != 0) {
-        continue;
-      }
-
-      if (param_name == name_ + "." + "map_subscribe_transient_local" ||
-        param_name == name_ + "." + "map_topic" ||
-        param_name == name_ + "." + "subscribe_to_updates")
-      {
-        RCLCPP_WARN(
+rcl_interfaces::msg::SetParametersResult
+StaticLayer::dynamicParametersCallback(std::vector<rclcpp::Parameter> parameters)
+{
+  std::lock_guard<Costmap2D::mutex_t> guard(*getMutex());
+  rcl_interfaces::msg::SetParametersResult result;
+
+  bool needs_full_update = false;
+
Error: +  for (auto parameter : parameters) {
+    const auto & param_type = parameter.get_type();
+    const auto & param_name = parameter.get_name();
+    if (param_name.find(name_ + ".") != 0) {
+      continue;
+    }
+
+    if (param_name == name_ + "." + "map_subscribe_transient_local" ||
+      param_name == name_ + "." + "map_topic" ||
+      param_name == name_ + "." + "subscribe_to_updates")
+    {
+      RCLCPP_WARN(
@@ -512,19 +512,18 @@
-      } else if (param_type == ParameterType::PARAMETER_DOUBLE) {
-        if (param_name == name_ + "." + "transform_tolerance") {
-          transform_tolerance_ = tf2::durationFromSec(parameter.as_double());
-        }
-
-      } else if (param_type == ParameterType::PARAMETER_BOOL) {
-
-        if (param_name == name_ + "." + "enabled" && enabled_ != parameter.as_bool()) {
-          enabled_ = parameter.as_bool();
-          needs_full_update = true;
-
-        } else if (param_name == name_ + "." + "footprint_clearing_enabled")
-        {
-          footprint_clearing_enabled_ = parameter.as_bool();
-        } else if (param_name == name_ + "." + "restore_cleared_footprint") {
-          if (footprint_clearing_enabled_) {
-              restore_cleared_footprint_ = parameter.as_bool();
-          } else {
-            RCLCPP_WARN(
+    } else if (param_type == ParameterType::PARAMETER_DOUBLE) {
+      if (param_name == name_ + "." + "transform_tolerance") {
+        transform_tolerance_ = tf2::durationFromSec(parameter.as_double());
+      }
+
+    } else if (param_type == ParameterType::PARAMETER_BOOL) {
+
+      if (param_name == name_ + "." + "enabled" && enabled_ != parameter.as_bool()) {
+        enabled_ = parameter.as_bool();
+        needs_full_update = true;
+
+      } else if (param_name == name_ + "." + "footprint_clearing_enabled") {
+        footprint_clearing_enabled_ = parameter.as_bool();
+      } else if (param_name == name_ + "." + "restore_cleared_footprint") {
+        if (footprint_clearing_enabled_) {
+          restore_cleared_footprint_ = parameter.as_bool();
+        } else {
+          RCLCPP_WARN(
@@ -533 +531,0 @@
-          }
@@ -536,18 +534,16 @@
-    }  
-
-    if (needs_full_update) {
-      x_ = y_ = 0;
-      width_ = size_x_;
-      height_ = size_y_;
-      has_updated_data_ = true;
-      current_ = false;
-    }
-
-    result.successful = true;
-    return result;
-  } // namespace nav2_costmap_2d
-
-}
-
-
-
+    }
+  }
+
+  if (needs_full_update) {
+    x_ = y_ = 0;
+    width_ = size_x_;
+    height_ = size_y_;
+    has_updated_data_ = true;
+    current_ = false;
+  }
+
+  result.successful = true;
+  return result;
+}   // namespace nav2_costmap_2d
+
+}

Code style divergence in file 'nav2_costmap_2d/plugins/voxel_layer.cpp':

--- nav2_costmap_2d/plugins/voxel_layer.cpp
+++ nav2_costmap_2d/plugins/voxel_layer.cpp.uncrustify
@@ -516 +516 @@
-        min_obstacle_height_ != parameter.as_double()) 
+        min_obstacle_height_ != parameter.as_double())
@@ -540,2 +540,2 @@
-      if (param_name == name_ + "." + "enabled" && 
-        enabled_ != parameter.as_bool()) 
+      if (param_name == name_ + "." + "enabled" &&
+        enabled_ != parameter.as_bool())
@@ -545 +545 @@
-      } else if (param_name == name_ + "." + "footprint_clearing_enabled"){
+      } else if (param_name == name_ + "." + "footprint_clearing_enabled") {

```

and/or

```

Error: /__w/navigation2/navigation2/nav2_costmap_2d/plugins/inflation_layer.cpp:448:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
Error: /__w/navigation2/navigation2/nav2_costmap_2d/plugins/obstacle_layer.cpp:374:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
Error: /__w/navigation2/navigation2/nav2_costmap_2d/plugins/static_layer.cpp:518:  Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
Error: /__w/navigation2/navigation2/nav2_costmap_2d/plugins/static_layer.cpp:523:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
Error: /__w/navigation2/navigation2/nav2_costmap_2d/plugins/static_layer.cpp:536:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
Error: /__w/navigation2/navigation2/nav2_costmap_2d/plugins/static_layer.cpp:548:  At least two spaces is best between code and comments  [whitespace/comments] [2]
Error: /__w/navigation2/navigation2/nav2_costmap_2d/plugins/static_layer.cpp:550:  Namespace should be terminated with "// namespace nav2_costmap_2d"  [readability/namespace] [5]
Error: /__w/navigation2/navigation2/nav2_costmap_2d/plugins/voxel_layer.cpp:516:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
Error: /__w/navigation2/navigation2/nav2_costmap_2d/plugins/voxel_layer.cpp:520:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
Error: /__w/navigation2/navigation2/nav2_costmap_2d/plugins/voxel_layer.cpp:525:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
Error: /__w/navigation2/navigation2/nav2_costmap_2d/plugins/voxel_layer.cpp:531:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
Error: /__w/navigation2/navigation2/nav2_costmap_2d/plugins/voxel_layer.cpp:540:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
Error: /__w/navigation2/navigation2/nav2_costmap_2d/plugins/voxel_layer.cpp:541:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]

```

(some may be duplicated)

You can see this yourself if you do `colcon test -packages-select nav2_costmap_2d` and then `colcon test-result --verbose` to see the failures. You may also directly run the linters via `ament_cpplint` `ament_uncrustify` etc

**Comment by MFarooq07** [comment]
Sounds good @tonynajjar ! I will fix the formatting.

**Comment by SteveMacenski** [comment]
@MFarooq07 relatedly: https://github.com/SteveMacenski/spatio_temporal_voxel_layer/issues/353

File: nav2_costmap_2d/plugins/static_layer.cpp [hunk 1]
```diff
@@ -486,55 +486,68 @@ bool StaticLayer::isEqual(double a, double b, double epsilon)
   * @brief Callback executed when a parameter change is detected
   * @param event ParameterEvent message
   */
-rcl_interfaces::msg::SetParametersResult
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/static_layer.cpp:489]: This file's changes are particularly not great and require alot of reverting of reformatting and reordering to be legible for review. The others are fine but have small errors that CI is bringing up. Please fix this up so we can review this meaningfully :-)

File: nav2_costmap_2d/plugins/static_layer.cpp [hunk 2]
```diff
@@ -505,36 +506,44 @@ StaticLayer::dynamicParametersCallback(
       param_name == name_ + "." + "subscribe_to_updates")
     {
       RCLCPP_WARN(
-        logger_, "%s is not a dynamic parameter "
-        "cannot be changed while running. Rejecting parameter update.", param_name.c_str());
+          logger_, "%s is not a dynamic parameter "
+          "cannot be changed while running. Rejecting parameter update.", param_name.c_str());
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/static_layer.cpp]: revert please

File: nav2_costmap_2d/plugins/static_layer.cpp [hunk 3]
```diff
@@ -505,36 +506,44 @@ StaticLayer::dynamicParametersCallback(
...
+
     } else if (param_type == ParameterType::PARAMETER_DOUBLE) {
       if (param_name == name_ + "." + "transform_tolerance") {
         transform_tolerance_ = tf2::durationFromSec(parameter.as_double());
       }
+
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/static_layer.cpp]: Revert

File: nav2_costmap_2d/plugins/static_layer.cpp [hunk 4]
```diff
@@ -505,36 +506,44 @@ StaticLayer::dynamicParametersCallback(
...
     } else if (param_type == ParameterType::PARAMETER_BOOL) {
+
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/static_layer.cpp]: Revert

File: nav2_costmap_2d/plugins/static_layer.cpp [hunk 5]
```diff
@@ -505,36 +506,44 @@ StaticLayer::dynamicParametersCallback(
...
       if (param_name == name_ + "." + "enabled" && enabled_ != parameter.as_bool()) {
         enabled_ = parameter.as_bool();
+        needs_full_update = true;
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/static_layer.cpp:517]: delete extra line

File: nav2_costmap_2d/plugins/static_layer.cpp [hunk 6]
```diff
@@ -505,36 +506,44 @@ StaticLayer::dynamicParametersCallback(
...
         footprint_clearing_enabled_ = parameter.as_bool();
       } else if (param_name == name_ + "." + "restore_cleared_footprint") {
         if (footprint_clearing_enabled_) {
           restore_cleared_footprint_ = parameter.as_bool();
         } else {
           RCLCPP_WARN(
-            logger_, "restore_cleared_footprint cannot be used "
-            "when footprint_clearing_enabled is False. Rejecting parameter update.");
+              logger_, "restore_cleared_footprint cannot be used "
+              "when footprint_clearing_enabled is False. Rejecting parameter update.");
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/static_layer.cpp]: Revert

File: nav2_costmap_2d/plugins/static_layer.cpp [hunk 7]
```diff
@@ -505,36 +506,44 @@ StaticLayer::dynamicParametersCallback(
...
+    width_ = size_x_;
+    height_ = size_y_;
+    has_updated_data_ = true;
+    current_ = false;
+  }
+
   result.successful = true;
   return result;
-}
+}   // namespace nav2_costmap_2d
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/static_layer.cpp]: Revert

**Comment by MFarooq07** [comment]
@SteveMacenski @tonynajjar I have tried to fix all the remaining formatting changes as suggested in the earlier. Let me know if there are any further edits that are required.

**Comment by tonynajjar** [comment]
You're running into the nasty conflict between ament_cpplint and ament_uncrustify https://github.com/ament/ament_lint/issues/158. I took the liberty to fix it for you

File: nav2_costmap_2d/plugins/voxel_layer.cpp [hunk 8]
```diff
@@ -537,13 +552,18 @@ VoxelLayer::dynamicParametersCallback(
       }
 
     } else if (param_type == ParameterType::PARAMETER_INTEGER) {
-      if (param_name == name_ + "." + "z_voxels") {
+      if (param_name == name_ + "." + "z_voxels" &&
+        size_z_ != parameter.as_int())
+      {
         size_z_ = parameter.as_int();
```
[the remark this answers is not in the document]
Comment (tonynajjar) [reply nav2_costmap_2d/plugins/voxel_layer.cpp:558]: @SteveMacenski that's not related to this PR but still a potential valid bug

File: nav2_costmap_2d/plugins/static_layer.cpp (hunk 3 above)
Comment (MFarooq07) [reply nav2_costmap_2d/plugins/static_layer.cpp]: fixed the formatting (undoing the indentation).

**Review by SteveMacenski — APPROVED** [review]
