### PR TITLE
Redesign dynamic parameters patterns for costmap and fix costmap tests

### LINKED ISSUE #5943: nav2_costmap_2d reports test success despite internal failures
```
25: [costmap_tests-4] [INFO 1770374255.630603724] [test_costmap.test_costmap]: Destroying
25: [costmap_tests-4] [WARN 1770374255.630609279] [rclcpp_lifecycle]: LifecycleNode is not shut down: Node still in state(1) in destructor
25: [costmap_tests-4] unknown file: Failure
25: [costmap_tests-4] C++ exception with description "parameter 'global_frame' cannot be set because it was not declared" thrown in the test body.
25: [costmap_tests-4] 
25: [costmap_tests-4] [  FAILED  ] TestNode.testDynParamsSet (2 ms)
25: [costmap_tests-4] [----------] 10 tests from TestNode (17 ms total)
25: [costmap_tests-4] 
25: [costmap_tests-4] [----------] Global test environment tear-down
25: [costmap_tests-4] [==========] 10 tests from 1 test suite ran. (17 ms total)
25: [costmap_tests-4] [  PASSED  ] 9 tests.
25: [costmap_tests-4] [  FAILED  ] 1 test, listed below:
25: [costmap_tests-4] [  FAILED  ] TestNode.testDynParamsSet
25: [costmap_tests-4] 
25: [costmap_tests-4]  1 FAILED TEST
25: [ERROR] [costmap_tests-4]: process has died [pid 1079878, exit code 1, cmd '/opt/auto_ws/build/nav2_costmap_2d/test/integration/inflation_tests_exec'].
25: [INFO] [launch]: process[costmap_tests-4] was required: shutting down launched system
25: [INFO] [lifecycle_manager-3]: sending signal 'SIGINT' to process[lifecycle_manager-3]
25: [INFO] [static_transform_publisher-2]: sending signal 'SIGINT' to process[static_transform_publisher-2]
25: [INFO] [map_server-1]: sending signal 'SIGINT' to process[map_server-1]
25: [lifecycle_manager-3] [INFO 1770374255.638471512] [rclcpp]: signal_handler(SIGINT/SIGTERM)
25: [lifecycle_manager-3] [INFO 1770374255.638548657] [lifecycle_manager]: Running Nav2 LifecycleManager rcl preshutdown (lifecycle_manager)
25: [lifecycle_manager-3] [INFO 1770374255.638589577] [lifecycle_manager]: Terminating bond timer...
25: [static_transform_publisher-2] [INFO 1770374255.638653190] [rclcpp]: signal_handler(SIGINT/SIGTERM)
25: [map_server-1] [INFO 1770374255.638755725] [rclcpp]: signal_handler(SIGINT/SIGTERM)
25: [map_server-1] [INFO 1770374255.638805524] [map_server]: Running Nav2 LifecycleNode rcl preshutdown (map_server)
25: [map_server-1] [INFO 1770374255.638846289] [map_server]: Deactivating
25: [map_server-1] [INFO 1770374255.638853997] [map_server]: Destroying bond (map_server) to lifecycle manager.
25: [INFO] [static_transform_publisher-2]: process has finished cleanly [pid 1079829]
25: [map_server-1] [INFO 1770374255.649101344] [map_server]: Cleaning up
25: [map_server-1] [INFO 1770374255.649155386] [map_server]: Destroying bond (map_server) to lifecycle manager.
25: [lifecycle_manager-3] [INFO 1770374255.649503660] [lifecycle_manager]: Destroying lifecycle_manager
25: [map_server-1] [INFO 1770374255.649706869] [map_server]: Destroying
25: [map_server-1] [WARN 1770374255.649732333] [rclcpp_lifecycle]: LifecycleNode is not shut down: Node still in state(1) in destructor
25: [INFO] [map_server-1]: process has finished cleanly [pid 1079828]
25: [INFO] [lifecycle_manager-3]: process has finished cleanly [pid 1079830]
25: -- run_test.py: return code 0
25: -- run_test.py: generate result file '/opt/auto_ws/build/nav2_costmap_2d/test_results/nav2_costmap_2d/inflation_tests.xml' with successful test
1/1 Test #25: inflation_tests ..................   Passed    1.39 sec

The following tests passed:
	inflation_tests

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   1.39 sec
Finished <<< nav2_costmap_2d [1.45s]
```

### PR DESCRIPTION
**Pull request by mini-1235**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | https://github.com/ros-navigation/navigation2/issues/4907 also fixes #5943 |
| Primary OS tested on | (Ubuntu, MacOS, Windows) |
| Robotic platform tested on | (Steve's Robot, gazebo simulation of Tally, hardware turtlebot) |
| Does this PR contain AI generated software? | (No; Yes and it is marked inline in the code) |
| Was this PR description generated by AI software? | Out of respect for maintainers, AI for human-to-human communications are banned |

---

## Description of how this change was tested

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists
- [ ] Should this be backported to current distributions? If so, tag with `backport-*`.

### CODE REVIEW

**Comment by mini-1235** [comment]
Pending https://github.com/ros-navigation/navigation2/issues/5943 to be fixed first

File: nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp [hunk 1]
```diff
@@ -97,6 +97,16 @@ class InflationLayer : public Layer
...
 
+  /**
+   * @brief Deactivate the layer
+   */
+  void deactivate() override;
+
+  /**
+   * @brief Activate the layer
+   */
+  void activate() override;
```
Comment (SteveMacenski) [inline nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp:108]: For the layers this is added: I don't see how/where these are ever called. I also would really like to not modify the costmap layer API if possible, since that's a non-trivial migration pattern for end-users (unless we really have to)

Comment (SteveMacenski) [reply nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp:108]: We could do the plugin initialize on the costmap `activate()` so that initialize can still setup the dynamic parameters

Comment (mini-1235) [reply nav2_costmap_2d/include/nav2_costmap_2d/inflation_layer.hpp:108]: They are actually called here
https://github.com/ros-navigation/navigation2/blob/913205382cb6a660505a026b4f83c07b7d787079/nav2_costmap_2d/src/costmap_2d_ros.cpp#L634-L644

I think they actually existed before but not implemented in inflation / voxel layer

File: nav2_costmap_2d/plugins/static_layer.cpp [hunk 2]
```diff
@@ -507,11 +509,33 @@ StaticLayer::dynamicParametersCallback(
...
         "cannot be changed while running. Rejecting parameter update.", param_name.c_str());
-    } else if (param_type == ParameterType::PARAMETER_DOUBLE) {
-      if (param_name == name_ + "." + "transform_tolerance") {
-        transform_tolerance_ = tf2::durationFromSec(parameter.as_double());
+    } else if (param_type == ParameterType::PARAMETER_BOOL && // NOLINT
+      param_name == name_ + "." + "restore_cleared_footprint")
+    {
+      if (!footprint_clearing_enabled_) {
+        RCLCPP_WARN(logger_, "restore_cleared_footprint cannot be used "
+                      "when footprint_clearing_enabled is False. Rejecting parameter update.");
```
Comment (SteveMacenski) [inline nav2_costmap_2d/plugins/static_layer.cpp]: Is this really the right linting?

**Comment by mini-1235** [comment]
> LGTM - is tehre worth adding some parameter validation to some of the files? Otherwise ready to go from my side

I usually scan through the `updateParameterCallback` + the documentation when adding validation logic. But given the large number of parameters, I wouldn't be surprised if I have missed a few. Please feel free to let me know if you notice any that you think are worth adding :)

**Comment by mini-1235** [comment]
It's kind of frustrating having to switch between branches just to retrigger the CI 🤒

**Comment by SteveMacenski** [comment]
I think its been enough time; I've upgraded your permissions to Write, so you can now push code and should then be accessible to retrigger CI as well. 

I would just ask that you be very cautious as you now have permissions to cause damage if you force push / don't manage branches on the main repo well :-)
