### PR TITLE
Revert #4971 in Jazzy

### LINKED ISSUE #5638: [Jazzy] [Controller server] Loading multiple controllers at the same time can result in parameter loading issue
## Bug report

**Required Info:**

- Operating System:
Ubuntu22.04
- Computer:
Thinkpad
- ROS2 Version:
Jazzy
- Version or commit hash:
v1.3.9
- DDS implementation:
CycloneDDS

#### Steps to reproduce issue

Start the controller server with two controller plugins. All the other parameters can be kept to their default value and let the lifecycle node configure the controller server.

```
controller_plugins: ["FollowPath1", "FollowPath2"]
FollowPath1:
  plugin: "nav2_rotation_shim_controller::RotationShimController"
  primary_controller: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

FollowPath2:
  plugin: "nav2_mppi_controller::MPPIController"
```

#### Expected behavior

Both controllers are loaded without error.

#### Actual behavior

The MPPI controller (second controller to be loaded) enters reports a fault in its configuration phase when loading the parameters as vx_min has a negative value. When checking into the code, raising an error when a parameter has a negative value is a behavior of the RPP controller. [1]

```
[controller_server-12] [INFO] [1761137974.303031720] [controller_server]: Created controller : FollowPath2 of type nav2_mppi_controller::MPPIController
[controller_server-12] [WARN] [1761137974.320779558] [controller_server]: The value of parameter 'FollowPath2.vx_min' is incorrectly set to -0.350000, it should be >=0. Ignoring parameter update.
[controller_server-12] [ERROR] [1761137974.321174478] [controller_server]: Caught exception in callback for transition 10
[controller_server-12] [ERROR] [1761137974.321264307] [controller_server]: Original error: parameter 'FollowPath2.vx_min' could not be set: 
[controller_server-12] [WARN] [1761137974.321337982] [controller_server]: Callback returned ERROR during the transition: configure
[controller_server-12] [FATAL] [1761137974.321372749] [controller_server]: Lifecycle node controller_server does not have error state implemented
[lifecycle_manager-16] [ERROR] [1761137974.332179778] [lifecycle_manager_navigation]: Failed to change state for node: controller_server
[lifecycle_manager-16] [ERROR] [1761137974.332315367] [lifecycle_manager_navigation]: Failed to bring up all requested nodes. Aborting bringup.
```

#### Reproduction instructions

The error happens when the node is re-configured, so no specific reproduction instruction here.

#### Additional information

[1] https://github.com/ros-navigation/navigation2/blob/7a609aeea79a69009994651f85ab53909b2bb30c/nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp#L229C1-L229C80

### PR DESCRIPTION
**Pull request by mini-1235**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | Fix #5638 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | turtlebot |
| Does this PR contain AI generated software? | (No; Yes and it is marked inline in the code) |
| Was this PR description generated by AI software? | Out of respect for maintainers, AI for human-to-human communications are banned |

---

## Description of how this change was tested

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists
- [ ] Should this be backported to current distributions? If so, tag with `backport-*`.

### CODE REVIEW

File: nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp [hunk 1]
```diff
@@ -295,10 +260,6 @@ ParameterHandler::updateParametersCallback(
         params_.cancel_deceleration = parameter.as_double();
       } else if (name == plugin_name_ + ".rotate_to_heading_min_angle") {
         params_.rotate_to_heading_min_angle = parameter.as_double();
-      } else if (name == plugin_name_ + ".transform_tolerance") {
-        params_.transform_tolerance = parameter.as_double();
-      } else if (name == plugin_name_ + ".max_robot_pose_search_dist") {
-        params_.max_robot_pose_search_dist = parameter.as_double();
       }
```
Comment (SteveMacenski) [inline nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp:267]: Should we keep these?

File: nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp [hunk 2]
```diff
@@ -318,12 +279,19 @@ ParameterHandler::updateParametersCallback(
...
       } else if (name == plugin_name_ + ".allow_reversing") {
+        if (params_.use_rotate_to_heading && parameter.as_bool()) {
+          RCLCPP_WARN(
+            logger_, "Both use_rotate_to_heading and allow_reversing "
+            "parameter cannot be set to true. Rejecting parameter update.");
+          continue;
+        }
         params_.allow_reversing = parameter.as_bool();
-      } else if (name == plugin_name_ + ".interpolate_curvature_after_goal") {
-        params_.interpolate_curvature_after_goal = parameter.as_bool();
```
Comment (SteveMacenski) [inline nav2_regulated_pure_pursuit_controller/src/parameter_handler.cpp:323]: Should we keep this?

**Review by SteveMacenski — APPROVED** [review]
