### PR TITLE
Fix the flaky dynamic params test thats been causing CI to fail

### LINKED ISSUE #556: nav2_dynamic_params test flaky.
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - source
- Version or commit hash:
  - master latest as of 5 Feb 2019
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue
Run colcon test

#### Expected behavior
Tests pass

#### Actual behavior
Occasionally `nav2_dynamic_params` will fail. It has now failed in CircleCI as well as on my local machine.

Ouput looks like
```
build/nav2_dynamic_params/test_results/nav2_dynamic_params/test_dynamic_params_client.xml: 1 test, 0 errors, 1 failure, 0 skipped
- nav2_dynamic_params test_dynamic_params_client.missing_result
  <<< failure message
    The test did not generate a result file:
    
    [INFO] [launch]: process[test_dynamic_params_helper-1]: started with pid [17615]
    [INFO] [launch]: process[test_dynamic_params_client-2]: started with pid [17616]
    [ERROR] [launch]: process[test_dynamic_params_client-2] process has died [pid 17616, exit code 1, cmd '/opt/nav2_ws/build/nav2_dynamic_params/test/test_dynamic_params_client_exec'].
    [INFO] [launch]: sending signal 'SIGINT' to process[test_dynamic_params_helper-1]
    [INFO] [launch]: process[test_dynamic_params_helper-1]: process has finished cleanly
  >>>
```

#### Additional information

See https://circleci.com/gh/ros-planning/navigation2/16 for an example of a failing run.

### PR DESCRIPTION
**Pull request by crdelsey**
**NOTE: I recommend reviewing this commit by commit rather than as one big PR**
_This is quite a big PR, but I cleaned up the commit history, so you can review it commit by commit. Each commit is an independent change if you follow it from oldest to newest. The newer ones build on the older ones._

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | partially addresses #556 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | NA |

---

## Description of contribution in a few bullet points

* Fixes dynamic params test that has been failing in CI. The test was failing because the "helper" nodes were not ready yet at the time the test started. I fixed this by converting the "helper" nodes to lifecycle nodes and waiting in the test till they were activated.

* This refactors and adds a bunch of support code, so this mechanism can be easily used on other tests that need it

---

### CODE REVIEW

**Comment by crdelsey** [comment]
Sorry for all the noise on this PR. It seems Github doesn't present commits in the order they are in the branch. Instead it shows them according to "author date".

**Comment by crdelsey** [comment]
I'd also like feedback on whether breaking the large PR into individually reviewable commits like this worked to make the review more manageable.

File: nav2_util/src/node_utils.cpp [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+  }
+  return output;
+}
+
+std::string generateInternalNodeName(const std::string & prefix)
+{
+  return sanitizeNodeName(prefix) + "_" + timeToString(8);
+}
+
+rclcpp::Node::SharedPtr generateInternalNode(const std::string & prefix)
```
Comment (mjeronimo) [inline nav2_util/src/node_utils.cpp]: Is this intended to be code generally available for the implementation to use or is it support code for testing (or both perhaps)? If it's testing-specific code, should we have a place for such code or is util the right place? I'm wondering if it's worth separating.

File: nav2_util/include/nav2_util/lifecycle_utils.hpp [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+
+#include <vector>
+#include <string>
+#include "nav2_util/string_utils.hpp"
+
+namespace nav2_util
+{
+
+/// Transition the given lifecycle nodes to the ACTIVATED state in order
+void bringupLifecycleNodes(const std::vector<std::string> & node_names);
```
[the remark this answers is not in the document]
Comment (crdelsey) [reply nav2_util/include/nav2_util/lifecycle_utils.hpp]: I agree. I wanted to make it super easy to write a test that uses lifecycle nodes, because I expect we will want to do that a lot to improve test stability.

I also didn't want to invest too much time into managing lifecycle states until you'd had a chance to look at this. I figured you probably had a better way to do this in the work you'd been doing.

File: nav2_util/include/nav2_util/service_client.hpp [hunk 3]
```diff
@@ -12,22 +12,29 @@
...
 {
 
 template<class ServiceT>
 class ServiceClient
 {
 public:
-  explicit ServiceClient(const std::string & name)
+  explicit ServiceClient(
+    const std::string & name,
+    const rclcpp::Node::SharedPtr & provided_node = rclcpp::Node::SharedPtr())
```
[the remark this answers is not in the document]
Comment (crdelsey) [reply nav2_util/include/nav2_util/service_client.hpp]: I believe that when we do the copy assignment of the reference to the member variable at `node_ = provided_node;`, that is when the reference will get incremented. 

By passing in a reference, we only avoid adding a temporary reference in the function parameter itself.

In other words, by passing the shared ptr by value instead of by ref, we create the parameter `provided_node` and increment the reference count. Then assign it to the member variable and increment the reference count again. When the function returns the parameter is destroyed and the reference counted is decremented again. 

We'd end up taking the shared ptr lock an extra two times for the sole purpose of the temporary parameter object.

File: nav2_util/src/node_utils.cpp (hunk 1 above)
Comment (crdelsey) [reply nav2_util/src/node_utils.cpp]: I was thinking it could be used anywhere we need to create a node internal to a class without bothering the client about that detail. So it would get used by ServiceClient, maybe DynamicParamsClient, and a few other places. It wasn't meant to be just for test code.

With some of the talk on the logger exception thread about nodes have unique names, I was afraid that these classes could end up creating nodes with identical names. I figured the solution to that was to add a randomized string to the end of the name, and I was trying to encapsulate the algorithm for that in this function.

File: nav2_util/src/lifecycle_utils.cpp [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+
+namespace nav2_util
+{
+
+void bringupLifecycleNode(const std::string & node_name)
+{
+  LifecycleServiceClient sc(node_name);
+  sc.ChangeState(lifecycle_msgs::msg::Transition::TRANSITION_CONFIGURE);
+  sc.ChangeState(lifecycle_msgs::msg::Transition::TRANSITION_ACTIVATE);
+  while (sc.GetState() != lifecycle_msgs::msg::State::PRIMARY_STATE_ACTIVE) {
```
[the remark this answers is not in the document]
Comment (crdelsey) [reply nav2_util/src/lifecycle_utils.cpp]: Yes. You're right. I was approaching this from the test mindset, where CMake or the user will Ctrl-C this if it takes too long.

I had to add the check for the current state being ACTIVE instead of just counting on the successful call to activate, but I don't remember why exactly. I'll retest to figure out why that was necessary.

File: nav2_tasks/include/nav2_tasks/global_localization_service_client.hpp [hunk 5]
```diff
@@ -15,24 +15,24 @@
...
 
-#include "nav2_tasks/service_client.hpp"
+#include "nav2_util/service_client.hpp"
 #include "std_srvs/srv/empty.hpp"
 
 namespace nav2_tasks
 {
 
-class globalLocalizationServiceClient : public ServiceClient<std_srvs::srv::Empty>
+class globalLocalizationServiceClient : public nav2_util::ServiceClient<std_srvs::srv::Empty>
```
Comment (orduno) [inline nav2_tasks/include/nav2_tasks/global_localization_service_client.hpp]: Should global be uppercase?

File: nav2_util/include/nav2_util/lifecycle_utils.hpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (crdelsey) [reply nav2_util/include/nav2_util/lifecycle_utils.hpp]: As I was went through this to separate test code from production code, I found I didn't have any test code to put in the library, so I'm going to defer creating that library.

This `bringupLifecycleNodes` function ended up being used by the command line utility I created, which I consider production code as opposed to just test code.

**Comment by crdelsey** [comment]
This change is necessary to make the dynamic params test stable, but is not enough in itself. The dynamic params test still fails sometimes when run concurrently with other tests. This will be addressed in another PR

File: nav2_tasks/include/nav2_tasks/global_localization_service_client.hpp (hunk 5 above)
Comment (crdelsey) [reply nav2_tasks/include/nav2_tasks/global_localization_service_client.hpp]: Yes. Fixed. As well as a bunch of other name violations in the nav2_utils package. I addressed all the functions in the main nav2_utils library, but left the libraries that came from AMCL and map server

File: nav2_util/include/nav2_util/service_client.hpp [hunk 6]
```diff
@@ -65,4 +65,4 @@ class ServiceClient
 
 }  // namespace nav2_tasks
 
-#endif  // NAV2_TASKS__SERVICE_CLIENT_HPP_
+#endif  // NAV2_UTIL__SERVICE_CLIENT_HPP_
```
Comment (mhpanah) [inline nav2_util/include/nav2_util/service_client.hpp]: This commit looks good.

File: nav2_util/src/node_utils.cpp [hunk 7]
```diff
@@ -0,0 +1,75 @@
...
+
+namespace nav2_util
+{
+
+string sanitizeNodeName(const string & potential_node_name)
+{
+  string node_name(potential_node_name);
+  // read this as `replace` characters in `node_name` `if` not alphanumeric.
+  // replace with '_'
+  replace_if(begin(node_name), end(node_name),
```
Comment (mhpanah) [inline nav2_util/src/node_utils.cpp]: Nice.

File: nav2_util/test/test_node_utils.cpp [hunk 8]
```diff
@@ -0,0 +1,49 @@
...
+  auto time2 = timeToString(8);
+  ASSERT_NE(time1, time2);
+}
+
+TEST(GenerateInternalNodeName, GenerateNodeName)
+{
+  auto defaultName = generateInternalNodeName();
+  ASSERT_EQ(defaultName[0], '_');
+  ASSERT_EQ(defaultName.length(), 9u);
+}
```
Comment (mhpanah) [inline nav2_util/test/test_node_utils.cpp]: This commit looks good.

File: nav2_util/test/test_service_client.cpp [hunk 9]
```diff
@@ -0,0 +1,46 @@
...
+  string name() {return node_->get_name();}
+};
+
+TEST(ServiceClient, service_name_with_slash)
+{
+  TestServiceClient t("/foo/bar");
+  string adjustedPrefix = "_foo_bar_Node_";
+  ASSERT_EQ(t.name().length(), adjustedPrefix.length() + 8);
+  ASSERT_EQ(0, t.name().compare(0, adjustedPrefix.length(), adjustedPrefix));
+}
```
Comment (mhpanah) [inline nav2_util/test/test_service_client.cpp]: This commit looks good.

File: nav2_util/src/lifecycle_utils.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (mhpanah) [reply nav2_util/src/lifecycle_utils.cpp]: Adding a timeout could help.

File: nav2_util/src/lifecycle_utils.cpp [hunk 10]
```diff
@@ -24,20 +24,46 @@ using std::string;
 namespace nav2_util
 {
 
-void bringupLifecycleNode(const std::string & node_name)
+#define RETRY(fn, retries) \
```
Comment (mhpanah) [inline nav2_util/src/lifecycle_utils.cpp]: There are other places in the code besides life-cycle that could benefit from this retry method.  For example for Auto Localization currently I'm using the BT retry node for this purpose but we might need a simple retry method for other tasks.

File: nav2_util/src/lifecycle_utils.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (crdelsey) [reply nav2_util/src/lifecycle_utils.cpp]: Done

File: nav2_util/src/lifecycle_utils.cpp (hunk 10 above)
Comment (crdelsey) [reply nav2_util/src/lifecycle_utils.cpp]: I agree. I'll do that as a separate PR. It seems like a big enough change that it should have a focused review and not just tacked on as an addendum to this one.
