### PR TITLE
Moves changes from PR #2083 to foxy

### LINKED ISSUE #2368: Moving fixes from PR #2083 into foxy-devel
## Bug report

**Required Info:**

- Operating System:
  - macOS 11
- ROS2 Version:
  - Foxy, from source
- Version or commit hash:
  - latest on `foxy-devel`
- DDS implementation:
  - Fast-DDS

Building on macOS was fixed by PR #2083 -- but those changes haven't gotten added to the foxy-devel branch, which is the branch people building for Foxy are expected to build off of. Is there a reason those changes haven't been cherry-picked over? I'd be happy to do it otherwise.

### PR DESCRIPTION
**Pull request by nkalupahana**
## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | Closes #2368 |
| Primary OS tested on | macOS |
| Robotic platform tested on | N/A |

---

## Description of contribution in a few bullet points

- Foxy branch now builds on macOS, based on fixes from PR #2083! Proof of build on CI: https://github.com/nkalupahana/ros2-foxy-macos/runs/2698988683?check_suite_focus=true

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in navigation.ros.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists

### CODE REVIEW

File: nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp [hunk 1]
```diff
@@ -229,7 +229,7 @@ geometry_msgs::msg::TwistStamped RegulatedPurePursuitController::computeVelocity
   // Find look ahead distance and point on path and publish
   const double lookahead_dist = getLookAheadDistance(speed);
   auto carrot_pose = getLookAheadPoint(lookahead_dist, transformed_plan);
-  carrot_pub_->publish(std::move(createCarrotMsg(carrot_pose)));
```
Comment (SteveMacenski) [inline nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp:232]: Change this back - we need to be publishing this as a unique pointer.

**Review by SteveMacenski — CHANGES_REQUESTED** [review]

File: nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp (hunk 1 above)
Comment (nkalupahana) [reply nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp:232]: Unfortunately, changing it back will lead to a build error:
```
/Users/runner/ws/src/navigation2/nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp:232:24: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
  carrot_pub_->publish(std::move(createCarrotMsg(carrot_pose)));
                       ^
/Users/runner/ws/src/navigation2/nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp:232:24: note: remove std::move call here
  carrot_pub_->publish(std::move(createCarrotMsg(carrot_pose)));
                       ^~~~~~~~~~                            ~
1 error generated.
```
Full CI Run: https://github.com/nkalupahana/ros2-foxy-macos/runs/2689457060?check_suite_focus=true

Comment (SteveMacenski) [reply nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp:232]: We publish almost everything using unique pointers, why is this particular publication a problem?

Comment (nkalupahana) [reply nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp:232]: This is still publishing with unique pointers -- all I've done here is remove `std::move`, as required by the compiler. This is because in C++17, when compiling with clang, the compiler requires that given certain circumstances (which are met here), the code is optimized to construct the object directly in the caller's stack frame, without ever constructing copies. std::move gets in the way of this.

Here's more information on this from a source that can explain it better than I can; see the `-Wpessimizing-move` section: https://developers.redhat.com/blog/2019/04/12/understanding-when-not-to-stdmove-in-c
GCC should also make this optimization since the C++ standard is set to C++17.

Let me know if this explains the change! TL;DR, removing `std::move` allows the compiler to make a more powerful optimization than `std::move`, and this optimization is required by clang on C++17.

Comment (SteveMacenski) [reply nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp:232]: OK, if you can submit these changes to `main` and they also build, I'd be OK merging this. I don't want to merge this into only `foxy`  though since it wouldn't apply to any future distributions (and our released distro CI isn't set up for non-member changes)

Comment (nkalupahana) [reply nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp:232]: Got it. Since this is the only change that isn't already in `main`, should I make a PR to main with just this change, then?

Comment (SteveMacenski) [reply nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp:232]: Yeah (you could also do Galactic if you like)

Comment (nkalupahana) [reply nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp:232]: Sounds good, I've done `main` and I'll do galactic in a minute.

Comment (nkalupahana) [reply nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp:232]: #2395 #2396
