### PR TITLE
Extended the SimpleActionServer interface

### LINKED ISSUE #835: Occasional failure of controller to follow the updated path.
## Bug report

**Required Info:**

- Operating System: Ubuntu 18.04
- Installation type: Source
- Version or commit hash: current HEAD-master c530cd89eb2e23cd4e9928c9df9dcdf21eaa042a
- DDS implementation: Fast-RTPS
- Client library (if applicable): rclcpp

#### Steps to reproduce the issue
To identify the failure we need to use goal preemption:

```
1. Run launch nav stack: $ ros2 launch nav2_bringup nav2_simulation_launch.py
2. Start nodes, provide an initial pose, provide end pose using the 'Navigation2 goal' tool
3. After the robot starts moving, provide a new goal pose using the 'Navigation2 goal' tool
```

#### Expected behavior
The robot is moving towards a goal. The goal is updated by the user and the Planner computes a path based on the new goal then the Controller follows the new path.

#### Actual behavior
Sporadically, after the user has provided an updated goal pose, the Planner does compute a path based on the new goal, however, the controller will continue to follow the old path towards the old goal pose.

#### Possible root cause
Two possible sources:

- More likely, there is some race condition between the time the new goal is received in `nav2_utils::SimpleActionServer` and when `dwb_controller` retrieves the update, causing DWB to still use an old goal handle.
- Less likely, `BT::BlackBoard` is not thread safe: the path updates are posted to the `BT::BlackBoard` before they are sent to DWB via ROS2 actions. The `BT::BlackBoard` is written/read asynchronously by the `ComputePath` and `FollowPath`.

### PR DESCRIPTION
**Pull request by orduno**
## Description of contribution in a few bullet points

Extended the `SimpleActionServer` interface and improved a few other things: 

* Added additional checks to make sure we only keep the latest preempt request in the queue.
* Action server users no longer interact directly with the goal handles. Provided additional functions for aborting, canceling, etc.
* Updated `bt_navigator`, `motion_primitives`, `dwb_controller`, `navfn_planner` to use the new interface.

Here's a diagram of the states and transitions:
SimpleActionServerStates

Refactored the DWB controller main loop:

* Changed the order of the steps to: 1) check for cancel 2) check for preempting 3) compute control 4) check if reached goal
* Made a few other small refactors.
* Added checks for handling pending preemptions after the controller has succeeded or failed.

This partially addresses #811 and possibly fix #835. Haven't been able to reproduce #835 to test.

---

## Future work that may be required in bullet points

* Fix the `SimpleActionServer` unit tests.
* Handle a pending preemption after reaching a final state on current goal #861.

### CODE REVIEW

**Comment by orduno** [comment]
I'll add a state diagram for `SimpleActionServer` to make it easier to review.

File: nav2_util/include/nav2_util/simple_action_server.hpp [hunk 1]
```diff
@@ -30,79 +30,215 @@ template<typename ActionT>
...
+    }
+
+    if (pending_handle_ != nullptr) {
+      warn_msg("Cancelling a pending goal. Should check for pre-empt requests before cancelling.");
+      pending_handle_->canceled(std::make_shared<typename ActionT::Result>());
+      pending_handle_.reset();
+    }
+  }
+
+  void abort_current_goal()
```
Comment (orduno) [inline nav2_util/include/nav2_util/simple_action_server.hpp]: Forgot to remove this method, not having reduces the number of possible states.

File: nav2_util/include/nav2_util/simple_action_server.hpp [hunk 2]
```diff
@@ -30,79 +30,215 @@ template<typename ActionT>
...
+
+    if (current_handle_ == nullptr) {
+      error_msg("Current goal is not available");
+      return false;
+    }
+
+    return current_handle_->is_canceling();
+  }
+
+  void cancel_current_goal()
```
Comment (orduno) [inline nav2_util/include/nav2_util/simple_action_server.hpp]: Forgot to remove this method, not having reduces the number of possible states.

File: nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp [hunk 3]
```diff
@@ -124,77 +123,112 @@ DwbController::on_shutdown(const rclcpp_lifecycle::State &)
...
+      action_server_->cancel_all();
+      publishZeroVelocity();
+      return true;
+    }
+  }
+
+  return false;
+}
+
+bool DwbController::checkPreemption()
```
Comment (crdelsey) [inline nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp]:
```suggestion
void DwbController::updateGlobalPath()
```
I think this name better reflects the behavior in terms of the DWB algorithm. Also, we do nothing with the return value, so why bother returning anything.

File: nav2_util/test/CMakeLists.txt [hunk 4]
```diff
@@ -17,6 +17,6 @@ ament_add_gtest(test_lifecycle_utils test_lifecycle_utils.cpp)
 ament_target_dependencies(test_lifecycle_utils rclcpp_lifecycle)
 target_link_libraries(test_lifecycle_utils ${library_name})
 
-ament_add_gtest(test_actions test_actions.cpp)
-ament_target_dependencies(test_actions rclcpp_action test_msgs)
-target_link_libraries(test_actions ${library_name})
+# ament_add_gtest(test_actions test_actions.cpp)
```
Comment (mhpanah) [inline nav2_util/test/CMakeLists.txt]: Why commenting these out?

File: nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp [hunk 5]
```diff
@@ -124,77 +123,112 @@ DwbController::on_shutdown(const rclcpp_lifecycle::State &)
...
+}
+
+bool DwbController::shouldCancel()
+{
+  // Check if the client requested a goal cancelation
+  if (action_server_->is_cancelling_current_goal()) {
+    RCLCPP_INFO(get_logger(), "Request to cancel the current goal was made.");
+
+    // Before cancelling, check if a new action is available
+    if (checkPreemption()) {
```
Comment (crdelsey) [inline nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp]: Can't we do this in the action server code? Why would it return that we should cancel when it knows we should really be preempting?

File: nav2_util/include/nav2_util/simple_action_server.hpp [hunk 6]
```diff
@@ -30,81 +30,218 @@ template<typename ActionT>
...
+    return std::make_shared<typename ActionT::Result>();
+  }
+
+  constexpr bool is_active(
+    const std::shared_ptr<rclcpp_action::ServerGoalHandle<ActionT>> handle) const
+  {
+    return handle != nullptr && handle->is_active();
+  }
+
+  void debug_msg(const std::string & msg) const
```
Comment (mhpanah) [inline nav2_util/include/nav2_util/simple_action_server.hpp]: Are these methods really needed?

File: nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp [hunk 7]
```diff
@@ -124,77 +123,112 @@ DwbController::on_shutdown(const rclcpp_lifecycle::State &)
...
+    setPlannerPath(action_server_->get_current_goal()->path);
     ProgressChecker progress_checker(rclcpp_node_);
 
-    rclcpp::Rate loop_rate(10);
+    rclcpp::Rate loop_rate(100ms);
     while (rclcpp::ok()) {
-      nav_2d_msgs::msg::Pose2DStamped pose2d;
-      if (!getRobotPose(pose2d)) {
-        RCLCPP_INFO(get_logger(), "No pose. Stopping the robot");
+      if (shouldCancel()) {
```
Comment (crdelsey) [inline nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp]: This does a lot more than just check if we should cancel. It changes state. I feel like the code should read more like

```
 while(rclcpp::ok()) {
  update_goal(goal_handle);
  if (goal_handle.empty())
    return;
```

update_goal would then handle the cancelling and preemption.

File: nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp [hunk 8]
```diff
@@ -124,77 +123,112 @@ DwbController::on_shutdown(const rclcpp_lifecycle::State &)
...
+  RCLCPP_DEBUG(get_logger(), "Path end point is (%.2f, %.2f)",
+    end_pose.position.x, end_pose.position.y);
+}
+
+bool DwbController::computeAndUpdate(ProgressChecker & progress_checker)
+{
+  nav_2d_msgs::msg::Pose2DStamped pose2d;
+
+  if (!getRobotPose(pose2d)) {
+    return false;
```
Comment (crdelsey) [inline nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp]: In the old code, this would trigger a call to `publish_zero_velocity`. Rather than add that back in here, I'm thinking it would make sense to just throw an exception, have DWB fail and publish_zero_velocity as part of the exception handler.

File: nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp [hunk 9]
```diff
@@ -124,77 +123,112 @@ DwbController::on_shutdown(const rclcpp_lifecycle::State &)
...
+  RCLCPP_DEBUG(get_logger(), "Providing path to the local planner");
+  planner_->setPlan(path2d);
+
+  auto end_pose = *(path.poses.end() - 1);
+
+  RCLCPP_DEBUG(get_logger(), "Path end point is (%.2f, %.2f)",
+    end_pose.position.x, end_pose.position.y);
+}
+
+bool DwbController::computeAndUpdate(ProgressChecker & progress_checker)
```
Comment (crdelsey) [inline nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp]:
```suggestion
bool DwbController::computeAndPublishVelocity(ProgressChecker & progress_checker)
```

File: nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp [hunk 10]
```diff
@@ -124,77 +123,112 @@ DwbController::on_shutdown(const rclcpp_lifecycle::State &)
...
-      nav_2d_msgs::msg::Pose2DStamped pose2d;
-      if (!getRobotPose(pose2d)) {
-        RCLCPP_INFO(get_logger(), "No pose. Stopping the robot");
+      if (shouldCancel()) {
+        return;
+      }
+
+      checkPreemption();
+
+      if (!computeAndUpdate(progress_checker)) {
```
Comment (crdelsey) [inline nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp]: I think I'd make the progress checker a member variable. It seems like an implementation detail to a high level function like this.

**Comment by crdelsey** [comment]
Comments on the statemachine drawing:

 On the `succeeded_current` transition from the `Pending Preemption` state, shouldn't it go to the `With Goal` state? The preempting goal should be the current one at that point?

File: nav2_dwb_controller/dwb_controller/include/dwb_controller/dwb_controller.hpp [hunk 11]
```diff
@@ -26,6 +26,7 @@
 #include "nav2_util/lifecycle_node.hpp"
 #include "nav2_msgs/action/follow_path.hpp"
 #include "nav2_util/simple_action_server.hpp"
+#include "dwb_controller/progress_checker.hpp"
```
Comment (mjeronimo) [inline nav2_dwb_controller/dwb_controller/include/dwb_controller/dwb_controller.hpp]: Not a big deal since we're not consistent with this, but since you're only using a reference you could declare the ProgressChecker class instead of including the header, then include the header in the implementation file.. This becomes more important on large projects when one is trying to keep compile time from getting out of hand.

File: nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp (hunk 7 above)
Comment (mjeronimo) [reply nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp]: I agree that it's a bit unexpected. Reading the code, I though shouldCancel would only tell me if I should cancel or not. However, it is returning if shouldCancel is true. However, the code doesn't do anything in response to knowing that it should cancel. Recommend reworking this section to clarify.

File: nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp [hunk 12]
```diff
@@ -124,77 +123,112 @@ DwbController::on_shutdown(const rclcpp_lifecycle::State &)
...
+    RCLCPP_INFO(get_logger(), "Request to cancel the current goal was made.");
+
+    // Before cancelling, check if a new action is available
+    if (checkPreemption()) {
+      RCLCPP_INFO(get_logger(), "Not cancelling since preemption was available.");
+      return false;
+    } else {
+      RCLCPP_INFO(get_logger(), "Cancelling and stopping.");
+      action_server_->cancel_all();
+      publishZeroVelocity();
```
Comment (mjeronimo) [inline nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp]: I don't think that publishing zero velocity should be here, down a level. I would expect to see that in the main loop's exit paths.

File: nav2_bt_navigator/src/bt_navigator.cpp [hunk 13]
```diff
@@ -160,22 +160,18 @@ BtNavigator::on_shutdown(const rclcpp_lifecycle::State & /*state*/)
...
-  auto result = std::make_shared<nav2_msgs::action::NavigateToPose::Result>();
-
-  initializeGoalPose(current_goal_handle);
+  initializeGoalPose();
 
   // Execute the BT that was previously created in the configure step
-  auto is_canceling = [&current_goal_handle]() -> bool
-    {return current_goal_handle->is_canceling();};
+  auto is_canceling =
+    [this]() -> bool {return action_server_->is_cancelling_current_goal();};
```
[the remark this answers is not in the document]
Comment (orduno) [reply nav2_bt_navigator/src/bt_navigator.cpp]: Will change that, I'm not committing the suggestion directly as we can now put the assignment next to the variable as it's shorter.

File: nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp (hunk 5 above)
Comment (orduno) [reply nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp]: @crdelsey Good point, we can set the cancellation policy as: if preempt available, cancel if the new goal is being canceled, otherwise cancel if the current goal is being canceled.

File: nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp (hunk 7 above)
Comment (orduno) [reply nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp]: Agree, I'll push a change.

File: nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp (hunk 10 above)
Comment (orduno) [reply nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp]: I'll change it.

File: nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp (hunk 8 above)
Comment (orduno) [reply nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp]: Agree, will change that.

File: nav2_dwb_controller/dwb_controller/include/dwb_controller/dwb_controller.hpp (hunk 11 above)
Comment (orduno) [reply nav2_dwb_controller/dwb_controller/include/dwb_controller/dwb_controller.hpp]: Agree, I'd like to start doing that. Will make a change.

File: nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp (hunk 12 above)
Comment (orduno) [reply nav2_dwb_controller/dwb_controller/src/dwb_controller.cpp]: Yeah, will fix that.

File: nav2_util/test/CMakeLists.txt (hunk 4 above)
Comment (orduno) [reply nav2_util/test/CMakeLists.txt]: I've updated the unit tests and re-enabled.

[the remark this answers is not in the document]
Comment (orduno) [reply nav2_util/test/CMakeLists.txt]: I've updated the unit tests and re-enabled.

**Comment by orduno** [comment]
> On the succeeded_current transition from the Pending Preemption state, shouldn't it go to the With Goal state? The preempting goal should be the current one at that point?

@crdelsey That transition is undesired. It means the owner of the action server didn't handle correctly a pending preemption. In that case, we succeed in the current goal and cancel the preemption.

https://github.com/ros-planning/navigation2/blob/620d12ae132ab3a2cf27056adcd8fab148f6adfb/nav2_util/include/nav2_util/simple_action_server.hpp#L204

**Comment by orduno** [comment]
@mhpanah @crdelsey @mjeronimo I've addressed your feedback. Please take a look.

File: nav2_dwb_controller/dwb_controller/include/dwb_controller/dwb_controller.hpp [hunk 14]
```diff
@@ -26,11 +26,12 @@
 #include "nav2_util/lifecycle_node.hpp"
 #include "nav2_msgs/action/follow_path.hpp"
 #include "nav2_util/simple_action_server.hpp"
-#include "dwb_controller/progress_checker.hpp"
 
 namespace dwb_controller
 {
 
+class ProgressChecker;
```
[the remark this answers is not in the document]
Comment (orduno) [reply nav2_dwb_controller/dwb_controller/include/dwb_controller/dwb_controller.hpp]: We addressed this offline.

File: nav2_navfn_planner/src/navfn_planner.cpp [hunk 15]
```diff
@@ -174,6 +172,17 @@ NavfnPlanner::computePathToPose()
       planner_->setNavArr(costmap_.metadata.size_x, costmap_.metadata.size_y);
     }
 
+    if (action_server_->is_cancelling()) {
```
[the remark this answers is not in the document]
Comment (orduno) [reply nav2_navfn_planner/src/navfn_planner.cpp]: Agree, will change it.
