### PR TITLE
Fix memory growth issue in isPoseOccupied

### LINKED ISSUE #5690: Memory grows overtime when calling service
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 24.02
- Computer:
  - AMD box
- ROS2 Version:
  - Kilted
- Version or commit hash:
  - 895c63ad155d494e2615809914e2f8a7dab8b47d
- DDS implementation:
  - CycloneDDS

#### Steps to reproduce issue

```
Calling isPoseOccupied in a tree xml config(https://github.com/ros-navigation/navigation2/blob/main/nav2_behavior_tree/plugins/condition/is_pose_occupied_condition.cpp)

```

#### Expected behavior
Memory consumption should not increase
#### Actual behavior
Memory consumption increase overtime
#### Additional information
The background of this behavior is that I am trying to get a cost at a goal pose to check if it is occupied, if it is, I will stop/pause the robot until the obstacle move away. So the plugin is called in a time manner.(1hz)
With 1Hz the memory grow slowly and if I increase to 10 or 100Hz, this will take a lot of memory after a short time.
Below is the heap consumption trace

Image

### PR DESCRIPTION
**Pull request by mini-1235**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | Fixes #5690 |
| Primary OS tested on | (Ubuntu, MacOS, Windows) |
| Robotic platform tested on | (Steve's Robot, gazebo simulation of Tally, hardware turtlebot) |
| Does this PR contain AI generated software? | (No; Yes and it is marked inline in the code) |
| Was this PR description generated by AI software? | Out of respect for maintainers, AI for human-to-human communications are banned |

---

## Description of how this change was tested

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists
- [ ] Should this be backported to current distributions? If so, tag with `backport-*`.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Once @chanhhoang99 approves, happy to merge

File: nav2_behavior_tree/plugins/condition/is_pose_occupied_condition.cpp [hunk 1]
```diff
@@ -24,24 +24,32 @@ IsPoseOccupiedCondition::IsPoseOccupiedCondition(
...
+
+void IsPoseOccupiedCondition::createROSInterfaces()
+{
+  std::string service_new;
+  getInput<std::string>("service_name", service_new);
+  if (service_new != service_name_ || !client_) {
+    service_name_ = service_new;
+    node_ = config().blackboard->get<nav2::LifecycleNode::SharedPtr>("node");
+    client_ =
+      node_->create_client<nav2_msgs::srv::GetCosts>(
```
Comment (chanhhoang99) [inline nav2_behavior_tree/plugins/condition/is_pose_occupied_condition.cpp:49]: client_ is a shared pointer, isn't that it got destroyed even if we create new one(like previous implementation) ?

Comment (mini-1235) [reply nav2_behavior_tree/plugins/condition/is_pose_occupied_condition.cpp:49]:
```
node_->create_client<nav2_msgs::srv::GetCosts>(
```

is a complex operation, and I am not familiar with these parts of code, so the following explanation might not be accurate.

When calling `client_->invoke(request, server_timeout_);`, if `client_` is replaced before the request finishes, the old client is destroyed. I would imagine that any pending requests belonging to the old client are lost, and their futures will never complete, thus causing memory growth.

Anyway, I don't see any reason to create the service client multiple times. It should be created once and re-created only if the service name has changed.

**Comment by SteveMacenski** [comment]
@chanhhoang99 does this solve the issue from your testing?

**Comment by chanhhoang99** [comment]
@SteveMacenski , I applied changes and tested for several hours yesterday. Memory is stable, no CPU usage increase.

File: nav2_behavior_tree/plugins/condition/is_pose_occupied_condition.cpp (hunk 1 above)
Comment (chanhhoang99) [reply nav2_behavior_tree/plugins/condition/is_pose_occupied_condition.cpp:49]: Okay I understand. Thanks alot.

**Comment by SteveMacenski** [comment]
Great! @mini-1235 can you change this from a draft?
