### PR TITLE
Move isStopped, isPathValid and isPoseOccupied from condition nodes to action nodes

### LINKED ISSUE #4881: BT Tick takes too long for some condition nodes
## Bug report

**Required Info:**

- Version or commit hash:
  - rolling head (13f728a)

#### Expected behavior
For all BT nodes, `tick` should return quickly.

#### Actual behavior
IsPathValid has `spin_until_future_complete`, which can take several ms to complete (that's a lot for a BT to be ticked at 100 Hz).
https://github.com/ros-navigation/navigation2/blob/13f728a67321102aadfe2843221f9da159c9d628/nav2_behavior_tree/plugins/condition/is_path_valid_condition.cpp#L53

Because this calls an action, its behavior should be equivalent to the action nodes inheriting from `BtActionNode`, returning RUNNING while the action is calculating. I've checked, I didn't see such spinning in a tick function in other condition nodes. Should this be transformed into an action node to prevent code duplication?

### PR DESCRIPTION
**Pull request by mini-1235**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | Fixes #4881 |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | (Steve's Robot, gazebo simulation of Tally, hardware turtlebot) |
| Does this PR contain AI generated software? | (No; Yes and it is marked inline in the code) |
| Was this PR description generated by AI software? | Out of respect for maintainers, AI for human-to-human communications are banned |

---

## Description of how this change was tested

---

#### For Maintainers: 
- [ ] Check that any new parameters added are updated in docs.nav2.org
- [ ] Check that any significant change is added to the migration guide
- [ ] Check that any new features **OR** changes to existing behaviors are reflected in the tuning guide
- [ ] Check that any new functions have Doxygen added
- [ ] Check that any new features have test coverage
- [ ] Check that any new plugins is added to the plugins page
- [ ] If BT Node, Additionally: add to BT's XML index of nodes for groot, BT package's readme table, and BT library lists
- [ ] Should this be backported to current distributions? If so, tag with `backport-*`.

### CODE REVIEW

**Comment by mini-1235** [comment]
Failing tests related to: #5987, #5990

**Comment by mini-1235** [comment]
@SteveMacenski There are quite a few places in the docs that need updating. I will open a PR there once you have done an initial review

**Comment by SteveMacenski** [comment]
I'm a bit behind today, I took a scan and nothing I immediately saw that caused concern. I still need to look through the implementations to make sure no capabilities were dropped / typos in conversion, but everything seems sane :+1:

**Comment by mini-1235** [comment]
```
+ EXCLUDE_PACKAGES='dwb_msgs nav2_msgs nav2_rviz_plugins nav2_system_tests nav_2d_msgs'
++ colcon list --names-only --packages-ignore dwb_msgs nav2_msgs nav2_rviz_plugins nav2_system_tests nav_2d_msgs
++ xargs
+ INCLUDE_PACKAGES='costmap_queue dwb_core dwb_critics dwb_plugins nav2_amcl nav2_behavior_tree nav2_behaviors nav2_bringup nav2_bt_navigator nav2_collision_monitor nav2_common nav2_constrained_smoother nav2_controller nav2_core nav2_costmap_2d nav2_dwb_controller nav2_graceful_controller nav2_lifecycle_manager nav2_loopback_sim nav2_map_server nav2_mppi_controller nav2_navfn_planner nav2_planner nav2_regulated_pure_pursuit_controller nav2_ros_common nav2_rotation_shim_controller nav2_route nav2_simple_commander nav2_smac_planner nav2_smoother nav2_theta_star_planner nav2_util nav2_velocity_smoother nav2_voxel_grid nav2_waypoint_follower nav_2d_utils navigation2 opennav_docking opennav_docking_bt opennav_docking_core opennav_following'
+ fastcov --lcov -d build --exclude test/ dwb_msgs nav2_msgs nav2_rviz_plugins nav2_system_tests nav_2d_msgs thirdparty/ --include costmap_queue dwb_core dwb_critics dwb_plugins nav2_amcl nav2_behavior_tree nav2_behaviors nav2_bringup nav2_bt_navigator nav2_collision_monitor nav2_common nav2_constrained_smoother nav2_controller nav2_core nav2_costmap_2d nav2_dwb_controller nav2_graceful_controller nav2_lifecycle_manager nav2_loopback_sim nav2_map_server nav2_mppi_controller nav2_navfn_planner nav2_planner nav2_regulated_pure_pursuit_controller nav2_ros_common nav2_rotation_shim_controller nav2_route nav2_simple_commander nav2_smac_planner nav2_smoother nav2_theta_star_planner nav2_util nav2_velocity_smoother nav2_voxel_grid nav2_waypoint_follower nav_2d_utils navigation2 opennav_docking opennav_docking_bt opennav_docking_core opennav_following --process-gcno --validate-sources --dump-statistic --output lcov/total_coverage.info
[0.125s] [info]: Found 1507 coverage files (.gcno)
[0.124s] [info]: Spawned 36 gcov processes, each processing at most 42 coverage files
[16.810s] [info]: Processed 3336 .gcov files (62964 total, 59628 skipped)
[0.024s] [error]: Could not find '/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/condition/is_path_valid_condition.cpp' to scan for exclusion markers...
[0.000s] [error]: Could not find '/opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/is_path_valid_condition.hpp' to scan for exclusion markers...
[0.000s] [error]: Could not find '/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/condition/is_pose_occupied_condition.cpp' to scan for exclusion markers...
[0.000s] [error]: Could not find '/opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/is_pose_occupied_condition.hpp' to scan for exclusion markers...
[0.000s] [error]: Could not find '/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/condition/is_stopped_condition.cpp' to scan for exclusion markers...
[0.000s] [error]: Could not find '/opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/is_stopped_condition.hpp' to scan for exclusion markers...
[0.033s] [info]: Spawned 36 exclusion marker scanning processes, each processing at most 20 source files
[0.005s] [info]: Scanned 708 source files for exclusion markers
[0.000s] [info]: Checking if all sources exist
[0.008s] [error]: Cannot find '/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/condition/is_path_valid_condition.cpp'
[0.000s] [error]: Cannot find '/opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/is_path_valid_condition.hpp'
[0.000s] [error]: Cannot find '/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/condition/is_pose_occupied_condition.cpp'
[0.000s] [error]: Cannot find '/opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/is_pose_occupied_condition.hpp'
[0.000s] [error]: Cannot find '/opt/overlay_ws/src/navigation2/nav2_behavior_tree/plugins/condition/is_stopped_condition.cpp'
[0.000s] [error]: Cannot find '/opt/overlay_ws/src/navigation2/nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/is_stopped_condition.hpp'
```

I will update the key since this PR remove some files

File: nav2_behavior_tree/plugins/action/check_pose_occupancy_action.cpp [hunk 1]
```diff
@@ -12,60 +12,40 @@
...
 
-IsPoseOccupiedCondition::IsPoseOccupiedCondition(
-  const std::string & condition_name,
+CheckPoseOccupancy::CheckPoseOccupancy(
+  const std::string & service_node_name,
   const BT::NodeConfiguration & conf)
-: BT::ConditionNode(condition_name, conf),
-  use_footprint_(true), consider_unknown_as_obstacle_(false), cost_threshold_(254)
+: BtServiceNode<nav2_msgs::srv::GetCosts>(service_node_name, conf,
+    "/global_costmap/get_cost_global_costmap")
```
Comment (SteveMacenski) [inline nav2_behavior_tree/plugins/action/check_pose_occupancy_action.cpp:28]: This needs to be parameterized

**Comment by mini-1235** [comment]
> But also I think there's a service name port, so is that overriding this default name when set? 

Yes, that's correct

File: nav2_behavior_tree/plugins/action/check_pose_occupancy_action.cpp (hunk 1 above)
Comment (mini-1235) [reply nav2_behavior_tree/plugins/action/check_pose_occupancy_action.cpp:28]: This is the default value after https://github.com/ros-navigation/navigation2/pull/5990, and only used when the the service name port is empty
