### PR TITLE
Fix DWB trajectory visualization

### LINKED ISSUE #447: Visualization of the controller trajectories in Rviz is poor
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 16.04
- Installation type:
  - source
- Version or commit hash:
  - 83034bbb13b, Dec 7 2018
- DDS implementation:
  - fast rtps
- Client library (if applicable):
  - 

#### Steps to reproduce issue

Visualization of the trajectories being evaluated by the DWB controller has various problems:
1. It is slow to update. The visualization only seems to update every second or so.
2. Artifacts of old data gets left on screen, making it difficult to tell what the current trajectories are.
3. Trajectories seem to show up only as solid blue, black or white. There should be a scaling of color from blue to white that shows the relative score.

image

### PR DESCRIPTION
**Pull request by crdelsey**
## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | fixes #447  |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | TB3 on Gazebo |

---

## Description of contribution in a few bullet points

* Code now ensures all markers are properly deleted. The trajectory markers are divided into two namespaces, one for valid trajectories and the other for invalid. Marker IDs are independent in the two namespaces, so both namespaces need to be cleaned up separately.
* Changed the valid trajectory color scheme to be solid blue for good trajectories, fading away for poor trajectories.

---

## Future work that may be required in bullet points

* The color scheme might need tweaking to better see what's going on. It seems trajectory scores right now are all clustered around the really good score and it is hard to see any difference. However, I think the scores themselves need to be investigated further before tweaking the display.
---

### CODE REVIEW

File: nav2_dwb_controller/dwb_core/include/dwb_core/publisher.hpp [hunk 1]
```diff
@@ -103,7 +110,7 @@ class DWBPublisher
   bool publish_cost_grid_pc_;
 
   // Previously published marker count for removing markers as needed
-  int prev_marker_count_;
+  unsigned prev_marker_count_;
```
Comment (orduno) [inline nav2_dwb_controller/dwb_core/include/dwb_core/publisher.hpp]: unsigned int?

Comment (crdelsey) [reply nav2_dwb_controller/dwb_core/include/dwb_core/publisher.hpp]: Our coding standard is silent on this. In the ros 2 source tree, I find it used with int 810 times and without 748 times. 

Seems there is no precedent. 

Do you want to try to standardize this for our project or leave it up to the individual?

Comment (orduno) [reply nav2_dwb_controller/dwb_core/include/dwb_core/publisher.hpp]: I'm OK with leaving it as is.
