### PR TITLE
Propagate task exceptions

### LINKED ISSUE #142: Correctly stop task servers upon outside failure
The task server code expects the command run to completion or for the client to cancel the task. There is another case where there is an external failure, such as an exception thrown such that the server's destructor is called without the task having succeeded, failed, or canceled. In this case,  the worker thread is not halted and the destructor waits forever to join the worker thread. Instead, the task server could automatically cancel the operation in this case, so that it correctly exits the worker thread.

### LINKED ISSUE #145: Propogate exceptions from TaskServer worker thread back to main thread.
If an uncaught exception occurs on the worker thread in `TaskServer`, it is not propagated back to the main thread, so it is never reported to the user, nor can be main handled in `main()`.

### PR DESCRIPTION
**Pull request by mjeronimo**
1). In the TaskServer template/base class, catch any exceptions generated by the derived class and return a failure status. 
2). Propagate this exception to the thread owning the object. 
3). Update the output messages in the SimpleNavigator to use the correct INFO, DEBUG, and ERROR macros instead of all using INFO. 

Fixes #142. Fixes #145.

### CODE REVIEW

File: nav2_robot/src/ros_robot.cpp [hunk 1]
```diff
@@ -23,17 +23,6 @@ namespace nav2_robot
 RosRobot::RosRobot(rclcpp::Node * node)
 : node_(node), initial_pose_received_(false), initial_odom_received_(false)
 {
-  // Open and parse the URDF file
```
Comment (mhpanah) [inline nav2_robot/src/ros_robot.cpp]: This has already been addressed in PR #175.

Comment (mjeronimo) [reply nav2_robot/src/ros_robot.cpp]: Sure, that'll be handled when I rebase.

File: nav2_tasks/include/nav2_tasks/task_server.hpp [hunk 2]
```diff
@@ -94,17 +94,22 @@ class TaskServer : public rclcpp::Node
...
       {
+        nav2_msgs::msg::TaskStatus statusMsg;
+	    TaskStatus status = TaskStatus::FAILED;
+
         // Call the user's overridden method
-        TaskStatus status = execute(commandMsg_);
+        try {
+          status = execute(commandMsg_);
+        } catch (...) {
+          statusMsg.result = nav2_msgs::msg::TaskStatus::FAILED;
```
Comment (crdelsey) [inline nav2_tasks/include/nav2_tasks/task_server.hpp]: This is important as well, but it's not exactly what I was looking for. I was looking for something more like this:
https://stackoverflow.com/questions/233127/how-can-i-propagate-exceptions-between-threads

With the change as written, the exception details are lost, and the worker thread keeps running.

I think we want something more like:
```c++
} catch (...) {
  exception_ptr_ = std::current_exception();
  statusMsg.result = nav2_msgs::msg::TaskStatus::FAILED;
  statusPub_->publish(statusMsg);
  return;
}
```
and then also:
```c++
void stopWorkerThread()
  {
    workerThread_->join();
    if (exception_ptr_ != nullptr)
      std::rethrow_exception(exception_ptr_);
    delete workerThread_;
    workerThread_ = nullptr;
}
```

**Comment by mkhansen-intel** [comment]
@mjeronimo - please rebase so that CI will run again, thanks!

File: nav2_tasks/include/nav2_tasks/task_server.hpp (hunk 2 above)
Comment (mjeronimo) [reply nav2_tasks/include/nav2_tasks/task_server.hpp]: I think of it like this: There are three "actors" here: the client, the task server (handling communication with the client and interfacing to the user's execute code), and the user's execute code. The client has invoked an operation which will return SUCCESS, FAILURE, or CANCELED. The task server's job is to invoke the execute code and return the result. If the user's execute code should generate an exception for a particular invocation of a task, I don't think that the task server should exit its operation (quit the thread). It can return failure and be ready to be invoked again. 

From a developer's point of view, we definitely need to understand what happened. The log messages provide that info. From the runtime perspective, I don't see that propagating the exception up higher would allow any kind of recovery or improved behavior. Instead, the task server would effectively be dead and couldn't be called again. It would have to be reloaded.

Comment (crdelsey) [reply nav2_tasks/include/nav2_tasks/task_server.hpp]: The way I see it, if the user's execute code should handle any exceptions they want to handle. If an exception makes it all the way to the task server code, we need to halt and report the problem. 

The task server should not be deciding the exception handling policy for the user's execute code.

As a user of the task server library, that is the behavior I want.

Comment (mjeronimo) [reply nav2_tasks/include/nav2_tasks/task_server.hpp]: Let's have a discussion to hash out the issues and summarize the results here. I'd like to talk about the interface to provide to task clients, how this intersects recovery, etc.

Comment (mjeronimo) [reply nav2_tasks/include/nav2_tasks/task_server.hpp]: Result of the discussion was that we'll implement it per Carl's suggestion. That is, propagate the exception to the thread that owns the TaskServer object. The TaskServer template will wrap the call to execute in a try/catch block. Upon an exception, it will save the exception in a member variable. The next job is to get the object to stop spinning so that it can reach its destructor and propagate the exception. For now, we'll use rclcpp::shutdown, but it would be better if there was a way to get this node to stop spinning. In the TaskServer destructure the exception will be propagated.

File: nav2_simple_navigator/src/simple_navigator.cpp [hunk 3]
```diff
@@ -28,49 +28,50 @@ SimpleNavigator::SimpleNavigator()
...
 {
-  RCLCPP_INFO(get_logger(), "SimpleNavigator::~SimpleNavigator");
+  RCLCPP_INFO(get_logger(), "Stopping node");
 }
 
 TaskStatus
 SimpleNavigator::execute(const nav2_tasks::NavigateToPoseCommand::SharedPtr command)
 {
-  RCLCPP_INFO(get_logger(), "SimpleNavigator::execute");
+  RCLCPP_DEBUG(get_logger(), "Execute");
```
[the remark this answers is not in the document]
Comment (mjeronimo) [reply nav2_simple_navigator/src/simple_navigator.cpp]: Yeah, I'll update it.

[the remark this answers is not in the document]
Comment (SteveMacenski) [reply nav2_simple_navigator/src/simple_navigator.cpp]: My PR #213 will redo that line anyhow - I wouldnt bother :)
